// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/auth/v1.yaml (models).
// DO NOT EDIT. Regenerate via: packages/contracts/go/generate.sh

// Package authv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authv1

import (
	"time"

	uuid "github.com/google/uuid"
)

// Defines values for ErrorErrorCode.
const (
	BadRequest          ErrorErrorCode = "bad_request"
	EmailTaken          ErrorErrorCode = "email_taken"
	InternalError       ErrorErrorCode = "internal_error"
	InvalidCredentials  ErrorErrorCode = "invalid_credentials"
	InvalidEmail        ErrorErrorCode = "invalid_email"
	InvalidRefreshToken ErrorErrorCode = "invalid_refresh_token"
	InvalidToken        ErrorErrorCode = "invalid_token"
	PasswordTooWeak     ErrorErrorCode = "password_too_weak"
	Unauthorized        ErrorErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case EmailTaken:
		return true
	case InternalError:
		return true
	case InvalidCredentials:
		return true
	case InvalidEmail:
		return true
	case InvalidRefreshToken:
		return true
	case InvalidToken:
		return true
	case PasswordTooWeak:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	Auth HealthResponseService = "auth"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case Auth:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok      HealthResponseStatus = "ok"
	Unready HealthResponseStatus = "unready"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// Defines values for PublicUserRole.
const (
	Admin PublicUserRole = "admin"
	User  PublicUserRole = "user"
)

// Valid indicates whether the value is a known member of the PublicUserRole enum.
func (e PublicUserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for PublicUserStatus.
const (
	Active   PublicUserStatus = "active"
	Disabled PublicUserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PublicUserStatus enum.
func (e PublicUserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Disabled:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenResponseTokenType enum.
func (e TokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Error Uniform error body. `code` is a stable machine-readable identifier;
// `message` is a human-readable string that never leaks internal
// implementation details, credentials or token material.
type Error struct {
	Error struct {
		Code    ErrorErrorCode `json:"code"`
		Message string         `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Emitting service identifier.
	Service HealthResponseService `json:"service"`

	// Status Liveness or readiness outcome.
	Status HealthResponseStatus `json:"status"`

	// Timestamp RFC 3339 UTC timestamp of the response.
	Timestamp time.Time `json:"timestamp"`
}

// HealthResponseService Emitting service identifier.
type HealthResponseService string

// HealthResponseStatus Liveness or readiness outcome.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken Opaque base64url refresh token.
	RefreshToken string `json:"refresh_token"`
}

// PublicUser Public user view. Never includes password or internal metadata.
type PublicUser struct {
	CreatedAt time.Time        `json:"created_at"`
	Email     string           `json:"email"`
	Id        uuid.UUID        `json:"id"`
	Role      PublicUserRole   `json:"role"`
	Status    PublicUserStatus `json:"status"`
}

// PublicUserRole defines model for PublicUser.Role.
type PublicUserRole string

// PublicUserStatus defines model for PublicUser.Status.
type PublicUserStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Opaque base64url refresh token.
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Normalized to lowercase and trimmed before processing.
	Email string `json:"email"`

	// Password Raw UTF-8; not trimmed and not NFKC-normalized. 12..128 Unicode
	// code points; no NUL or control characters.
	Password string `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Ed25519 (EdDSA) JWT access token.
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Opaque base64url refresh token.
	RefreshToken string                 `json:"refresh_token"`
	TokenType    TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest
