// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/auth/v1.yaml (models).
// DO NOT EDIT. Regenerate via: packages/contracts/go/generate.sh
// Package authv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authv1

import (
	"time"

	uuid "github.com/google/uuid"
)

// Defines values for AdminApiKeyStatus.
const (
	AdminApiKeyStatusActive   AdminApiKeyStatus = "active"
	AdminApiKeyStatusDisabled AdminApiKeyStatus = "disabled"
)

// Valid indicates whether the value is a known member of the AdminApiKeyStatus enum.
func (e AdminApiKeyStatus) Valid() bool {
	switch e {
	case AdminApiKeyStatusActive:
		return true
	case AdminApiKeyStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for AdminUpdateUserRequestRole.
const (
	AdminUpdateUserRequestRoleAdmin AdminUpdateUserRequestRole = "admin"
	AdminUpdateUserRequestRoleUser  AdminUpdateUserRequestRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUpdateUserRequestRole enum.
func (e AdminUpdateUserRequestRole) Valid() bool {
	switch e {
	case AdminUpdateUserRequestRoleAdmin:
		return true
	case AdminUpdateUserRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUpdateUserRequestStatus.
const (
	AdminUpdateUserRequestStatusActive   AdminUpdateUserRequestStatus = "active"
	AdminUpdateUserRequestStatusDisabled AdminUpdateUserRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the AdminUpdateUserRequestStatus enum.
func (e AdminUpdateUserRequestStatus) Valid() bool {
	switch e {
	case AdminUpdateUserRequestStatusActive:
		return true
	case AdminUpdateUserRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserRole.
const (
	AdminUserRoleAdmin AdminUserRole = "admin"
	AdminUserRoleUser  AdminUserRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserRole enum.
func (e AdminUserRole) Valid() bool {
	switch e {
	case AdminUserRoleAdmin:
		return true
	case AdminUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserStatus.
const (
	AdminUserStatusActive   AdminUserStatus = "active"
	AdminUserStatusDisabled AdminUserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the AdminUserStatus enum.
func (e AdminUserStatus) Valid() bool {
	switch e {
	case AdminUserStatusActive:
		return true
	case AdminUserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyStatus.
const (
	ApiKeyStatusActive   ApiKeyStatus = "active"
	ApiKeyStatusDisabled ApiKeyStatus = "disabled"
)

// Valid indicates whether the value is a known member of the ApiKeyStatus enum.
func (e ApiKeyStatus) Valid() bool {
	switch e {
	case ApiKeyStatusActive:
		return true
	case ApiKeyStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyCreatedStatus.
const (
	ApiKeyCreatedStatusActive ApiKeyCreatedStatus = "active"
)

// Valid indicates whether the value is a known member of the ApiKeyCreatedStatus enum.
func (e ApiKeyCreatedStatus) Valid() bool {
	switch e {
	case ApiKeyCreatedStatusActive:
		return true
	default:
		return false
	}
}

// Defines values for ErrorErrorCode.
const (
	BadRequest          ErrorErrorCode = "bad_request"
	EmailTaken          ErrorErrorCode = "email_taken"
	Forbidden           ErrorErrorCode = "forbidden"
	InternalError       ErrorErrorCode = "internal_error"
	InvalidCredentials  ErrorErrorCode = "invalid_credentials"
	InvalidEmail        ErrorErrorCode = "invalid_email"
	InvalidRefreshToken ErrorErrorCode = "invalid_refresh_token"
	InvalidToken        ErrorErrorCode = "invalid_token"
	NotFound            ErrorErrorCode = "not_found"
	PasswordTooWeak     ErrorErrorCode = "password_too_weak"
	Unauthorized        ErrorErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case EmailTaken:
		return true
	case Forbidden:
		return true
	case InternalError:
		return true
	case InvalidCredentials:
		return true
	case InvalidEmail:
		return true
	case InvalidRefreshToken:
		return true
	case InvalidToken:
		return true
	case NotFound:
		return true
	case PasswordTooWeak:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseService.
const (
	Auth HealthResponseService = "auth"
)

// Valid indicates whether the value is a known member of the HealthResponseService enum.
func (e HealthResponseService) Valid() bool {
	switch e {
	case Auth:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok      HealthResponseStatus = "ok"
	Unready HealthResponseStatus = "unready"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	case Unready:
		return true
	default:
		return false
	}
}

// Defines values for PublicUserRole.
const (
	PublicUserRoleAdmin PublicUserRole = "admin"
	PublicUserRoleUser  PublicUserRole = "user"
)

// Valid indicates whether the value is a known member of the PublicUserRole enum.
func (e PublicUserRole) Valid() bool {
	switch e {
	case PublicUserRoleAdmin:
		return true
	case PublicUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PublicUserStatus.
const (
	PublicUserStatusActive   PublicUserStatus = "active"
	PublicUserStatusDisabled PublicUserStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PublicUserStatus enum.
func (e PublicUserStatus) Valid() bool {
	switch e {
	case PublicUserStatusActive:
		return true
	case PublicUserStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for TokenResponseTokenType.
const (
	Bearer TokenResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenResponseTokenType enum.
func (e TokenResponseTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UpdateApiKeyRequestStatus.
const (
	UpdateApiKeyRequestStatusActive   UpdateApiKeyRequestStatus = "active"
	UpdateApiKeyRequestStatusDisabled UpdateApiKeyRequestStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateApiKeyRequestStatus enum.
func (e UpdateApiKeyRequestStatus) Valid() bool {
	switch e {
	case UpdateApiKeyRequestStatusActive:
		return true
	case UpdateApiKeyRequestStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for VerifiedIdentityRole.
const (
	VerifiedIdentityRoleAdmin VerifiedIdentityRole = "admin"
	VerifiedIdentityRoleUser  VerifiedIdentityRole = "user"
)

// Valid indicates whether the value is a known member of the VerifiedIdentityRole enum.
func (e VerifiedIdentityRole) Valid() bool {
	switch e {
	case VerifiedIdentityRoleAdmin:
		return true
	case VerifiedIdentityRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for VerifiedIdentityStatus.
const (
	VerifiedIdentityStatusActive   VerifiedIdentityStatus = "active"
	VerifiedIdentityStatusDisabled VerifiedIdentityStatus = "disabled"
)

// Valid indicates whether the value is a known member of the VerifiedIdentityStatus enum.
func (e VerifiedIdentityStatus) Valid() bool {
	switch e {
	case VerifiedIdentityStatusActive:
		return true
	case VerifiedIdentityStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for AuthAdminListUsersParamsStatus.
const (
	AuthAdminListUsersParamsStatusActive   AuthAdminListUsersParamsStatus = "active"
	AuthAdminListUsersParamsStatusDisabled AuthAdminListUsersParamsStatus = "disabled"
)

// Valid indicates whether the value is a known member of the AuthAdminListUsersParamsStatus enum.
func (e AuthAdminListUsersParamsStatus) Valid() bool {
	switch e {
	case AuthAdminListUsersParamsStatusActive:
		return true
	case AuthAdminListUsersParamsStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for AuthAdminListUsersParamsRole.
const (
	AuthAdminListUsersParamsRoleAdmin AuthAdminListUsersParamsRole = "admin"
	AuthAdminListUsersParamsRoleUser  AuthAdminListUsersParamsRole = "user"
)

// Valid indicates whether the value is a known member of the AuthAdminListUsersParamsRole enum.
func (e AuthAdminListUsersParamsRole) Valid() bool {
	switch e {
	case AuthAdminListUsersParamsRoleAdmin:
		return true
	case AuthAdminListUsersParamsRoleUser:
		return true
	default:
		return false
	}
}

// AdminApiKey Admin API key view (cross-user). Includes `user_id` for ownership.
// Key secrets are never returned.
type AdminApiKey struct {
	CreatedAt  time.Time         `json:"created_at"`
	ExpiresAt  *time.Time        `json:"expires_at,omitempty"`
	Id         uuid.UUID         `json:"id"`
	KeyPrefix  string            `json:"key_prefix"`
	KeySuffix  string            `json:"key_suffix"`
	LastUsedAt *time.Time        `json:"last_used_at,omitempty"`
	Name       string            `json:"name"`
	Status     AdminApiKeyStatus `json:"status"`
	UserId     uuid.UUID         `json:"user_id"`
}

// AdminApiKeyStatus defines model for AdminApiKey.Status.
type AdminApiKeyStatus string

// AdminUpdateUserRequest Modifiable user fields for admin. At least one field is required.
type AdminUpdateUserRequest struct {
	Role   *AdminUpdateUserRequestRole   `json:"role,omitempty"`
	Status *AdminUpdateUserRequestStatus `json:"status,omitempty"`
}

// AdminUpdateUserRequestRole defines model for AdminUpdateUserRequest.Role.
type AdminUpdateUserRequestRole string

// AdminUpdateUserRequestStatus defines model for AdminUpdateUserRequest.Status.
type AdminUpdateUserRequestStatus string

// AdminUser Admin user view. Never includes password hash or internal metadata.
type AdminUser struct {
	CreatedAt time.Time       `json:"created_at"`
	Email     string          `json:"email"`
	Id        uuid.UUID       `json:"id"`
	Role      AdminUserRole   `json:"role"`
	Status    AdminUserStatus `json:"status"`
}

// AdminUserRole defines model for AdminUser.Role.
type AdminUserRole string

// AdminUserStatus defines model for AdminUser.Status.
type AdminUserStatus string

// ApiKey Public API key view. The full secret is never returned; only
// `key_prefix` and `key_suffix` are exposed for identification.
type ApiKey struct {
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration time, or null if the key never expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id        uuid.UUID  `json:"id"`

	// KeyPrefix First characters of the key for display.
	KeyPrefix string `json:"key_prefix"`

	// KeySuffix Last characters of the key for display.
	KeySuffix string `json:"key_suffix"`

	// LastUsedAt Last successful verification, or null if never used.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name Human-readable key name.
	Name string `json:"name"`

	// Status Lifecycle status. `revoked` is never exposed to owners.
	Status ApiKeyStatus `json:"status"`
}

// ApiKeyStatus Lifecycle status. `revoked` is never exposed to owners.
type ApiKeyStatus string

// ApiKeyCreated API key with its full secret. Returned only on create and rotate;
// the secret is never retrievable again.
type ApiKeyCreated struct {
	CreatedAt time.Time `json:"created_at"`
	Id        uuid.UUID `json:"id"`
	KeyPrefix string    `json:"key_prefix"`
	KeySuffix string    `json:"key_suffix"`
	Name      string    `json:"name"`

	// Secret Full API key secret — only returned on create/rotate.
	Secret string              `json:"secret"`
	Status ApiKeyCreatedStatus `json:"status"`
}

// ApiKeyCreatedStatus defines model for ApiKeyCreated.Status.
type ApiKeyCreatedStatus string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	// ExpiresAt Optional expiration time.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Name Optional human-readable key name.
	Name *string `json:"name,omitempty"`
}

// Error Uniform error body. `code` is a stable machine-readable identifier;
// `message` is a human-readable string that never leaks internal
// implementation details, credentials or token material.
type Error struct {
	Error struct {
		Code    ErrorErrorCode `json:"code"`
		Message string         `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Service Emitting service identifier.
	Service HealthResponseService `json:"service"`

	// Status Liveness or readiness outcome.
	Status HealthResponseStatus `json:"status"`

	// Timestamp RFC 3339 UTC timestamp of the response.
	Timestamp time.Time `json:"timestamp"`
}

// HealthResponseService Emitting service identifier.
type HealthResponseService string

// HealthResponseStatus Liveness or readiness outcome.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	// RefreshToken Opaque base64url refresh token.
	RefreshToken string `json:"refresh_token"`
}

// PublicUser Public user view. Never includes password or internal metadata.
type PublicUser struct {
	CreatedAt time.Time        `json:"created_at"`
	Email     string           `json:"email"`
	Id        uuid.UUID        `json:"id"`
	Role      PublicUserRole   `json:"role"`
	Status    PublicUserStatus `json:"status"`
}

// PublicUserRole defines model for PublicUser.Role.
type PublicUserRole string

// PublicUserStatus defines model for PublicUser.Status.
type PublicUserStatus string

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	// RefreshToken Opaque base64url refresh token.
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Email Normalized to lowercase and trimmed before processing.
	Email string `json:"email"`

	// Password Raw UTF-8; not trimmed and not NFKC-normalized. 12..128 Unicode
	// code points; no NUL or control characters.
	Password string `json:"password"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// AccessToken Ed25519 (EdDSA) JWT access token.
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Opaque base64url refresh token.
	RefreshToken string                 `json:"refresh_token"`
	TokenType    TokenResponseTokenType `json:"token_type"`
}

// TokenResponseTokenType defines model for TokenResponse.TokenType.
type TokenResponseTokenType string

// UpdateApiKeyRequest defines model for UpdateApiKeyRequest.
type UpdateApiKeyRequest struct {
	// Name New human-readable key name.
	Name *string `json:"name,omitempty"`

	// Status New lifecycle status.
	Status *UpdateApiKeyRequestStatus `json:"status,omitempty"`
}

// UpdateApiKeyRequestStatus New lifecycle status.
type UpdateApiKeyRequestStatus string

// VerifiedIdentity defines model for VerifiedIdentity.
type VerifiedIdentity struct {
	Email *string `json:"email,omitempty"`

	// KeyId The verified API key ID.
	KeyId  *string                `json:"key_id,omitempty"`
	Role   VerifiedIdentityRole   `json:"role"`
	Status VerifiedIdentityStatus `json:"status"`
	UserId string                 `json:"user_id"`
}

// VerifiedIdentityRole defines model for VerifiedIdentity.Role.
type VerifiedIdentityRole string

// VerifiedIdentityStatus defines model for VerifiedIdentity.Status.
type VerifiedIdentityStatus string

// VerifyKeyRequest defines model for VerifyKeyRequest.
type VerifyKeyRequest struct {
	// ApiKey Opaque API key with `tmp_` prefix.
	ApiKey string `json:"api_key"`
}

// KeyId defines model for KeyId.
type KeyId = uuid.UUID

// UserIdPath defines model for UserIdPath.
type UserIdPath = uuid.UUID

// AuthAdminListKeysParams defines parameters for AuthAdminListKeys.
type AuthAdminListKeysParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// AuthAdminListUsersParams defines parameters for AuthAdminListUsers.
type AuthAdminListUsersParams struct {
	// Search Optional email substring filter.
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// Status Optional status filter (active or disabled).
	Status *AuthAdminListUsersParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Role Optional role filter (user or admin).
	Role     *AuthAdminListUsersParamsRole `form:"role,omitempty" json:"role,omitempty"`
	Page     *int                          `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int                          `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// AuthAdminListUsersParamsStatus defines parameters for AuthAdminListUsers.
type AuthAdminListUsersParamsStatus string

// AuthAdminListUsersParamsRole defines parameters for AuthAdminListUsers.
type AuthAdminListUsersParamsRole string

// AuthAdminUpdateUserJSONRequestBody defines body for AuthAdminUpdateUser for application/json ContentType.
type AuthAdminUpdateUserJSONRequestBody = AdminUpdateUserRequest

// AuthCreateApiKeyJSONRequestBody defines body for AuthCreateApiKey for application/json ContentType.
type AuthCreateApiKeyJSONRequestBody = CreateApiKeyRequest

// AuthUpdateApiKeyJSONRequestBody defines body for AuthUpdateApiKey for application/json ContentType.
type AuthUpdateApiKeyJSONRequestBody = UpdateApiKeyRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// AuthVerifyKeyJSONRequestBody defines body for AuthVerifyKey for application/json ContentType.
type AuthVerifyKeyJSONRequestBody = VerifyKeyRequest
