// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/auth/v1.yaml (Chi and strict server).
// DO NOT EDIT. Regenerate via: packages/contracts/go/generate.sh

// Package authv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// AuthListApiKeys List API keys
	// (GET /api/v1/auth/keys)
	AuthListApiKeys(w http.ResponseWriter, r *http.Request)
	// AuthCreateApiKey Create an API key
	// (POST /api/v1/auth/keys)
	AuthCreateApiKey(w http.ResponseWriter, r *http.Request)
	// AuthDeleteApiKey Revoke an API key
	// (DELETE /api/v1/auth/keys/{keyId})
	AuthDeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// AuthGetApiKey Get API key details
	// (GET /api/v1/auth/keys/{keyId})
	AuthGetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// AuthUpdateApiKey Modify an API key
	// (PATCH /api/v1/auth/keys/{keyId})
	AuthUpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// AuthRotateApiKey Rotate an API key
	// (POST /api/v1/auth/keys/{keyId}/rotate)
	AuthRotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Log out (revoke a single refresh token)
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// LogoutAll Log out everywhere
	// (POST /api/v1/auth/logout-all)
	LogoutAll(w http.ResponseWriter, r *http.Request)
	// Me Current user
	// (GET /api/v1/auth/me)
	Me(w http.ResponseWriter, r *http.Request)
	// ChangePassword Change password
	// (PUT /api/v1/auth/password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// Refresh Rotate a refresh token
	// (POST /api/v1/auth/refresh)
	Refresh(w http.ResponseWriter, r *http.Request)
	// Register Register a new user
	// (POST /api/v1/auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// HeadHealthz Liveness probe (HEAD)
	// (HEAD /healthz)
	HeadHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// HeadReadyz Readiness probe (HEAD)
	// (HEAD /readyz)
	HeadReadyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// AuthListApiKeys List API keys
// (GET /api/v1/auth/keys)
func (_ Unimplemented) AuthListApiKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthCreateApiKey Create an API key
// (POST /api/v1/auth/keys)
func (_ Unimplemented) AuthCreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthDeleteApiKey Revoke an API key
// (DELETE /api/v1/auth/keys/{keyId})
func (_ Unimplemented) AuthDeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthGetApiKey Get API key details
// (GET /api/v1/auth/keys/{keyId})
func (_ Unimplemented) AuthGetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthUpdateApiKey Modify an API key
// (PATCH /api/v1/auth/keys/{keyId})
func (_ Unimplemented) AuthUpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AuthRotateApiKey Rotate an API key
// (POST /api/v1/auth/keys/{keyId}/rotate)
func (_ Unimplemented) AuthRotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Log in
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Log out (revoke a single refresh token)
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutAll Log out everywhere
// (POST /api/v1/auth/logout-all)
func (_ Unimplemented) LogoutAll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Me Current user
// (GET /api/v1/auth/me)
func (_ Unimplemented) Me(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChangePassword Change password
// (PUT /api/v1/auth/password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh Rotate a refresh token
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register Register a new user
// (POST /api/v1/auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HeadHealthz Liveness probe (HEAD)
// (HEAD /healthz)
func (_ Unimplemented) HeadHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadyz Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// HeadReadyz Readiness probe (HEAD)
// (HEAD /readyz)
func (_ Unimplemented) HeadReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AuthListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) AuthListApiKeys(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthListApiKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthCreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) AuthCreateApiKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthCreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthDeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) AuthDeleteApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthDeleteApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthGetApiKey operation middleware
func (siw *ServerInterfaceWrapper) AuthGetApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthGetApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthUpdateApiKey operation middleware
func (siw *ServerInterfaceWrapper) AuthUpdateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthUpdateApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthRotateApiKey operation middleware
func (siw *ServerInterfaceWrapper) AuthRotateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthRotateApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutAll operation middleware
func (siw *ServerInterfaceWrapper) LogoutAll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutAll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Me(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadHealthz operation middleware
func (siw *ServerInterfaceWrapper) HeadHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadReadyz operation middleware
func (siw *ServerInterfaceWrapper) HeadReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/healthz", wrapper.HeadHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/readyz", wrapper.HeadReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout-all", wrapper.LogoutAll)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.Me)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/auth/password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/keys", wrapper.AuthListApiKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/keys", wrapper.AuthCreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/auth/keys/{keyId}", wrapper.AuthDeleteApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/keys/{keyId}", wrapper.AuthGetApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/auth/keys/{keyId}", wrapper.AuthUpdateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/keys/{keyId}/rotate", wrapper.AuthRotateApiKey)
	})

	return r
}

type AuthListApiKeysRequestObject struct {
}

type AuthListApiKeysResponseObject interface {
	VisitAuthListApiKeysResponse(w http.ResponseWriter) error
}

type AuthListApiKeys200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthListApiKeys200JSONResponse struct {
	Body struct {
		Keys []ApiKey `json:"keys"`
	}
	Headers AuthListApiKeys200ResponseHeaders
}

func (response AuthListApiKeys200JSONResponse) VisitAuthListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthListApiKeys401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthListApiKeys401JSONResponse struct {
	Body    Error
	Headers AuthListApiKeys401ResponseHeaders
}

func (response AuthListApiKeys401JSONResponse) VisitAuthListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthListApiKeys500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthListApiKeys500JSONResponse struct {
	Body    Error
	Headers AuthListApiKeys500ResponseHeaders
}

func (response AuthListApiKeys500JSONResponse) VisitAuthListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCreateApiKeyRequestObject struct {
	Body *AuthCreateApiKeyJSONRequestBody
}

type AuthCreateApiKeyResponseObject interface {
	VisitAuthCreateApiKeyResponse(w http.ResponseWriter) error
}

type AuthCreateApiKey201ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthCreateApiKey201JSONResponse struct {
	Body struct {
		// Key API key with its full secret. Returned only on create and rotate;
		// the secret is never retrievable again.
		Key ApiKeyCreated `json:"key"`
	}
	Headers AuthCreateApiKey201ResponseHeaders
}

func (response AuthCreateApiKey201JSONResponse) VisitAuthCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCreateApiKey400ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthCreateApiKey400JSONResponse struct {
	Body    Error
	Headers AuthCreateApiKey400ResponseHeaders
}

func (response AuthCreateApiKey400JSONResponse) VisitAuthCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCreateApiKey401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthCreateApiKey401JSONResponse struct {
	Body    Error
	Headers AuthCreateApiKey401ResponseHeaders
}

func (response AuthCreateApiKey401JSONResponse) VisitAuthCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthCreateApiKey500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthCreateApiKey500JSONResponse struct {
	Body    Error
	Headers AuthCreateApiKey500ResponseHeaders
}

func (response AuthCreateApiKey500JSONResponse) VisitAuthCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AuthDeleteApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type AuthDeleteApiKeyResponseObject interface {
	VisitAuthDeleteApiKeyResponse(w http.ResponseWriter) error
}

type AuthDeleteApiKey204ResponseHeaders struct {
	CacheControl *string
}

type AuthDeleteApiKey204Response struct {
	Headers AuthDeleteApiKey204ResponseHeaders
}

func (response AuthDeleteApiKey204Response) VisitAuthDeleteApiKeyResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type AuthDeleteApiKey401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthDeleteApiKey401JSONResponse struct {
	Body    Error
	Headers AuthDeleteApiKey401ResponseHeaders
}

func (response AuthDeleteApiKey401JSONResponse) VisitAuthDeleteApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthDeleteApiKey404ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthDeleteApiKey404JSONResponse struct {
	Body    Error
	Headers AuthDeleteApiKey404ResponseHeaders
}

func (response AuthDeleteApiKey404JSONResponse) VisitAuthDeleteApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AuthDeleteApiKey500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthDeleteApiKey500JSONResponse struct {
	Body    Error
	Headers AuthDeleteApiKey500ResponseHeaders
}

func (response AuthDeleteApiKey500JSONResponse) VisitAuthDeleteApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AuthGetApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type AuthGetApiKeyResponseObject interface {
	VisitAuthGetApiKeyResponse(w http.ResponseWriter) error
}

type AuthGetApiKey200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthGetApiKey200JSONResponse struct {
	Body struct {
		// Key Public API key view. The full secret is never returned; only
		// `key_prefix` and `key_suffix` are exposed for identification.
		Key ApiKey `json:"key"`
	}
	Headers AuthGetApiKey200ResponseHeaders
}

func (response AuthGetApiKey200JSONResponse) VisitAuthGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthGetApiKey401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthGetApiKey401JSONResponse struct {
	Body    Error
	Headers AuthGetApiKey401ResponseHeaders
}

func (response AuthGetApiKey401JSONResponse) VisitAuthGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthGetApiKey404ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthGetApiKey404JSONResponse struct {
	Body    Error
	Headers AuthGetApiKey404ResponseHeaders
}

func (response AuthGetApiKey404JSONResponse) VisitAuthGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AuthGetApiKey500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthGetApiKey500JSONResponse struct {
	Body    Error
	Headers AuthGetApiKey500ResponseHeaders
}

func (response AuthGetApiKey500JSONResponse) VisitAuthGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AuthUpdateApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
	Body  *AuthUpdateApiKeyJSONRequestBody
}

type AuthUpdateApiKeyResponseObject interface {
	VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error
}

type AuthUpdateApiKey200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthUpdateApiKey200JSONResponse struct {
	Body struct {
		// Key Public API key view. The full secret is never returned; only
		// `key_prefix` and `key_suffix` are exposed for identification.
		Key ApiKey `json:"key"`
	}
	Headers AuthUpdateApiKey200ResponseHeaders
}

func (response AuthUpdateApiKey200JSONResponse) VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthUpdateApiKey400ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthUpdateApiKey400JSONResponse struct {
	Body    Error
	Headers AuthUpdateApiKey400ResponseHeaders
}

func (response AuthUpdateApiKey400JSONResponse) VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AuthUpdateApiKey401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthUpdateApiKey401JSONResponse struct {
	Body    Error
	Headers AuthUpdateApiKey401ResponseHeaders
}

func (response AuthUpdateApiKey401JSONResponse) VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthUpdateApiKey404ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthUpdateApiKey404JSONResponse struct {
	Body    Error
	Headers AuthUpdateApiKey404ResponseHeaders
}

func (response AuthUpdateApiKey404JSONResponse) VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AuthUpdateApiKey500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthUpdateApiKey500JSONResponse struct {
	Body    Error
	Headers AuthUpdateApiKey500ResponseHeaders
}

func (response AuthUpdateApiKey500JSONResponse) VisitAuthUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type AuthRotateApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type AuthRotateApiKeyResponseObject interface {
	VisitAuthRotateApiKeyResponse(w http.ResponseWriter) error
}

type AuthRotateApiKey200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthRotateApiKey200JSONResponse struct {
	Body struct {
		// Key API key with its full secret. Returned only on create and rotate;
		// the secret is never retrievable again.
		Key ApiKeyCreated `json:"key"`
	}
	Headers AuthRotateApiKey200ResponseHeaders
}

func (response AuthRotateApiKey200JSONResponse) VisitAuthRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthRotateApiKey401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthRotateApiKey401JSONResponse struct {
	Body    Error
	Headers AuthRotateApiKey401ResponseHeaders
}

func (response AuthRotateApiKey401JSONResponse) VisitAuthRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AuthRotateApiKey404ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthRotateApiKey404JSONResponse struct {
	Body    Error
	Headers AuthRotateApiKey404ResponseHeaders
}

func (response AuthRotateApiKey404JSONResponse) VisitAuthRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AuthRotateApiKey500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type AuthRotateApiKey500JSONResponse struct {
	Body    Error
	Headers AuthRotateApiKey500ResponseHeaders
}

func (response AuthRotateApiKey500JSONResponse) VisitAuthRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Login200JSONResponse struct {
	Body    TokenResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Login400JSONResponse struct {
	Body    Error
	Headers Login400ResponseHeaders
}

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Login401JSONResponse struct {
	Body    Error
	Headers Login401ResponseHeaders
}

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Login500JSONResponse struct {
	Body    Error
	Headers Login500ResponseHeaders
}

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	CacheControl *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutAllRequestObject struct {
}

type LogoutAllResponseObject interface {
	VisitLogoutAllResponse(w http.ResponseWriter) error
}

type LogoutAll204ResponseHeaders struct {
	CacheControl *string
}

type LogoutAll204Response struct {
	Headers LogoutAll204ResponseHeaders
}

func (response LogoutAll204Response) VisitLogoutAllResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type LogoutAll401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type LogoutAll401JSONResponse struct {
	Body    Error
	Headers LogoutAll401ResponseHeaders
}

func (response LogoutAll401JSONResponse) VisitLogoutAllResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutAll500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type LogoutAll500JSONResponse struct {
	Body    Error
	Headers LogoutAll500ResponseHeaders
}

func (response LogoutAll500JSONResponse) VisitLogoutAllResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type MeRequestObject struct {
}

type MeResponseObject interface {
	VisitMeResponse(w http.ResponseWriter) error
}

type Me200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Me200JSONResponse struct {
	Body    PublicUser
	Headers Me200ResponseHeaders
}

func (response Me200JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Me401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Me401JSONResponse struct {
	Body    Error
	Headers Me401ResponseHeaders
}

func (response Me401JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Me500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Me500JSONResponse struct {
	Body    Error
	Headers Me500ResponseHeaders
}

func (response Me500JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword204ResponseHeaders struct {
	CacheControl *string
}

type ChangePassword204Response struct {
	Headers ChangePassword204ResponseHeaders
}

func (response ChangePassword204Response) VisitChangePasswordResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(204)
	return nil
}

type ChangePassword400ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type ChangePassword400JSONResponse struct {
	Body    Error
	Headers ChangePassword400ResponseHeaders
}

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type ChangePassword401JSONResponse struct {
	Body    Error
	Headers ChangePassword401ResponseHeaders
}

func (response ChangePassword401JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type ChangePassword500JSONResponse struct {
	Body    Error
	Headers ChangePassword500ResponseHeaders
}

func (response ChangePassword500JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshRequestObject struct {
	Body *RefreshJSONRequestBody
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Refresh200JSONResponse struct {
	Body    TokenResponse
	Headers Refresh200ResponseHeaders
}

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh401ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Refresh401JSONResponse struct {
	Body    Error
	Headers Refresh401ResponseHeaders
}

func (response Refresh401JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Refresh500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Refresh500JSONResponse struct {
	Body    Error
	Headers Refresh500ResponseHeaders
}

func (response Refresh500JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Register201JSONResponse struct {
	Body    PublicUser
	Headers Register201ResponseHeaders
}

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Register400JSONResponse struct {
	Body    Error
	Headers Register400ResponseHeaders
}

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Register409JSONResponse struct {
	Body    Error
	Headers Register409ResponseHeaders
}

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register500ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type Register500JSONResponse struct {
	Body    Error
	Headers Register500ResponseHeaders
}

func (response Register500JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type GetHealthz200JSONResponse struct {
	Body    HealthResponse
	Headers GetHealthz200ResponseHeaders
}

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz405ResponseHeaders struct {
	CacheControl *string
}

type GetHealthz405Response struct {
	Headers GetHealthz405ResponseHeaders
}

func (response GetHealthz405Response) VisitGetHealthzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(405)
	return nil
}

type HeadHealthzRequestObject struct {
}

type HeadHealthzResponseObject interface {
	VisitHeadHealthzResponse(w http.ResponseWriter) error
}

type HeadHealthz200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type HeadHealthz200Response struct {
	Headers HeadHealthz200ResponseHeaders
}

func (response HeadHealthz200Response) VisitHeadHealthzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	return nil
}

type HeadHealthz405ResponseHeaders struct {
	CacheControl *string
}

type HeadHealthz405Response struct {
	Headers HeadHealthz405ResponseHeaders
}

func (response HeadHealthz405Response) VisitHeadHealthzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(405)
	return nil
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type GetReadyz200JSONResponse struct {
	Body    HealthResponse
	Headers GetReadyz200ResponseHeaders
}

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz405ResponseHeaders struct {
	CacheControl *string
}

type GetReadyz405Response struct {
	Headers GetReadyz405ResponseHeaders
}

func (response GetReadyz405Response) VisitGetReadyzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(405)
	return nil
}

type GetReadyz503ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type GetReadyz503JSONResponse struct {
	Body    HealthResponse
	Headers GetReadyz503ResponseHeaders
}

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type HeadReadyzRequestObject struct {
}

type HeadReadyzResponseObject interface {
	VisitHeadReadyzResponse(w http.ResponseWriter) error
}

type HeadReadyz200ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type HeadReadyz200Response struct {
	Headers HeadReadyz200ResponseHeaders
}

func (response HeadReadyz200Response) VisitHeadReadyzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(200)
	return nil
}

type HeadReadyz405ResponseHeaders struct {
	CacheControl *string
}

type HeadReadyz405Response struct {
	Headers HeadReadyz405ResponseHeaders
}

func (response HeadReadyz405Response) VisitHeadReadyzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(405)
	return nil
}

type HeadReadyz503ResponseHeaders struct {
	CacheControl *string
	ContentType  *string
}

type HeadReadyz503Response struct {
	Headers HeadReadyz503ResponseHeaders
}

func (response HeadReadyz503Response) VisitHeadReadyzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	if response.Headers.ContentType != nil {
		w.Header().Set("Content-Type", fmt.Sprint(*response.Headers.ContentType))
	}
	w.WriteHeader(503)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// AuthListApiKeys List API keys
	// (GET /api/v1/auth/keys)
	AuthListApiKeys(ctx context.Context, request AuthListApiKeysRequestObject) (AuthListApiKeysResponseObject, error)
	// AuthCreateApiKey Create an API key
	// (POST /api/v1/auth/keys)
	AuthCreateApiKey(ctx context.Context, request AuthCreateApiKeyRequestObject) (AuthCreateApiKeyResponseObject, error)
	// AuthDeleteApiKey Revoke an API key
	// (DELETE /api/v1/auth/keys/{keyId})
	AuthDeleteApiKey(ctx context.Context, request AuthDeleteApiKeyRequestObject) (AuthDeleteApiKeyResponseObject, error)
	// AuthGetApiKey Get API key details
	// (GET /api/v1/auth/keys/{keyId})
	AuthGetApiKey(ctx context.Context, request AuthGetApiKeyRequestObject) (AuthGetApiKeyResponseObject, error)
	// AuthUpdateApiKey Modify an API key
	// (PATCH /api/v1/auth/keys/{keyId})
	AuthUpdateApiKey(ctx context.Context, request AuthUpdateApiKeyRequestObject) (AuthUpdateApiKeyResponseObject, error)
	// AuthRotateApiKey Rotate an API key
	// (POST /api/v1/auth/keys/{keyId}/rotate)
	AuthRotateApiKey(ctx context.Context, request AuthRotateApiKeyRequestObject) (AuthRotateApiKeyResponseObject, error)
	// Login Log in
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Log out (revoke a single refresh token)
	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// LogoutAll Log out everywhere
	// (POST /api/v1/auth/logout-all)
	LogoutAll(ctx context.Context, request LogoutAllRequestObject) (LogoutAllResponseObject, error)
	// Me Current user
	// (GET /api/v1/auth/me)
	Me(ctx context.Context, request MeRequestObject) (MeResponseObject, error)
	// ChangePassword Change password
	// (PUT /api/v1/auth/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Refresh Rotate a refresh token
	// (POST /api/v1/auth/refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Register Register a new user
	// (POST /api/v1/auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// HeadHealthz Liveness probe (HEAD)
	// (HEAD /healthz)
	HeadHealthz(ctx context.Context, request HeadHealthzRequestObject) (HeadHealthzResponseObject, error)
	// GetReadyz Readiness probe
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// HeadReadyz Readiness probe (HEAD)
	// (HEAD /readyz)
	HeadReadyz(ctx context.Context, request HeadReadyzRequestObject) (HeadReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AuthListApiKeys operation middleware
func (sh *strictHandler) AuthListApiKeys(w http.ResponseWriter, r *http.Request) {
	var request AuthListApiKeysRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthListApiKeys(ctx, request.(AuthListApiKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthListApiKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthListApiKeysResponseObject); ok {
		if err := validResponse.VisitAuthListApiKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthCreateApiKey operation middleware
func (sh *strictHandler) AuthCreateApiKey(w http.ResponseWriter, r *http.Request) {
	var request AuthCreateApiKeyRequestObject

	var body AuthCreateApiKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthCreateApiKey(ctx, request.(AuthCreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthCreateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthCreateApiKeyResponseObject); ok {
		if err := validResponse.VisitAuthCreateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthDeleteApiKey operation middleware
func (sh *strictHandler) AuthDeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request AuthDeleteApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthDeleteApiKey(ctx, request.(AuthDeleteApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthDeleteApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthDeleteApiKeyResponseObject); ok {
		if err := validResponse.VisitAuthDeleteApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthGetApiKey operation middleware
func (sh *strictHandler) AuthGetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request AuthGetApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthGetApiKey(ctx, request.(AuthGetApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthGetApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthGetApiKeyResponseObject); ok {
		if err := validResponse.VisitAuthGetApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthUpdateApiKey operation middleware
func (sh *strictHandler) AuthUpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request AuthUpdateApiKeyRequestObject

	request.KeyId = keyId

	var body AuthUpdateApiKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthUpdateApiKey(ctx, request.(AuthUpdateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthUpdateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthUpdateApiKeyResponseObject); ok {
		if err := validResponse.VisitAuthUpdateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthRotateApiKey operation middleware
func (sh *strictHandler) AuthRotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request AuthRotateApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthRotateApiKey(ctx, request.(AuthRotateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthRotateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthRotateApiKeyResponseObject); ok {
		if err := validResponse.VisitAuthRotateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LogoutAll operation middleware
func (sh *strictHandler) LogoutAll(w http.ResponseWriter, r *http.Request) {
	var request LogoutAllRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutAll(ctx, request.(LogoutAllRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutAll")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutAllResponseObject); ok {
		if err := validResponse.VisitLogoutAllResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Me operation middleware
func (sh *strictHandler) Me(w http.ResponseWriter, r *http.Request) {
	var request MeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Me(ctx, request.(MeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Me")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MeResponseObject); ok {
		if err := validResponse.VisitMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	var request RefreshRequestObject

	var body RefreshJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadHealthz operation middleware
func (sh *strictHandler) HeadHealthz(w http.ResponseWriter, r *http.Request) {
	var request HeadHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeadHealthz(ctx, request.(HeadHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeadHealthzResponseObject); ok {
		if err := validResponse.VisitHeadHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadReadyz operation middleware
func (sh *strictHandler) HeadReadyz(w http.ResponseWriter, r *http.Request) {
	var request HeadReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeadReadyz(ctx, request.(HeadReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeadReadyzResponseObject); ok {
		if err := validResponse.VisitHeadReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
