#!/usr/bin/env bash
# generate-executor.sh — Generate Executor v1 Go models and Chi/strict server code.
#
# Reads:   packages/contracts/openapi/executor/v1.yaml
# Configs: packages/contracts/go/executor-v1-{models,server}.yaml
# Outputs: services/executor/internal/contract/executorv1/{models,server}.gen.go
#
# Usage: ./generate-executor.sh [OUTPUT_DIR]
# OUTPUT_DIR defaults to services/executor/internal/contract/executorv1.

set -euo pipefail

OAPI_CODEGEN_VERSION="v2.8.0"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
CONTRACT="${REPO_ROOT}/packages/contracts/openapi/executor/v1.yaml"
MODELS_CONFIG="${SCRIPT_DIR}/executor-v1-models.yaml"
SERVER_CONFIG="${SCRIPT_DIR}/executor-v1-server.yaml"
OUTPUT_DIR="${1:-${REPO_ROOT}/services/executor/internal/contract/executorv1}"

for input in "$CONTRACT" "$MODELS_CONFIG" "$SERVER_CONFIG"; do
  if [ ! -f "$input" ]; then
    echo "ERROR: required generation input not found: $input" >&2
    exit 1
  fi
done

mkdir -p "$OUTPUT_DIR"
cd "$REPO_ROOT"

generate_file() {
  local config="$1"
  local output="$2"
  local kind="$3"
  local temporary

  temporary="$(mktemp)"
  trap 'rm -f "$temporary"' RETURN
  go run "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@${OAPI_CODEGEN_VERSION}" \
    --config "$config" \
    "$CONTRACT" > "$temporary"
  {
    printf '%s\n' "// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/executor/v1.yaml (${kind})."
    printf '%s\n\n' '// DO NOT EDIT. Regenerate via: packages/contracts/go/generate-executor.sh'
    cat "$temporary"
  } > "$output"
  gofmt -w "$output"
  rm -f "$temporary"
  trap - RETURN
  echo "Generated: $output"
}

echo "Generating Executor v1 Go code with oapi-codegen ${OAPI_CODEGEN_VERSION}..."
generate_file "$MODELS_CONFIG" "$OUTPUT_DIR/models.gen.go" "models"
generate_file "$SERVER_CONFIG" "$OUTPUT_DIR/server.gen.go" "Chi and strict server"
