// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiKeyStatus.
const (
	ApiKeyStatusActive   ApiKeyStatus = "active"
	ApiKeyStatusDisabled ApiKeyStatus = "disabled"
)

// Valid indicates whether the value is a known member of the ApiKeyStatus enum.
func (e ApiKeyStatus) Valid() bool {
	switch e {
	case ApiKeyStatusActive:
		return true
	case ApiKeyStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ApiKeyCreatedStatus.
const (
	ApiKeyCreatedStatusActive ApiKeyCreatedStatus = "active"
)

// Valid indicates whether the value is a known member of the ApiKeyCreatedStatus enum.
func (e ApiKeyCreatedStatus) Valid() bool {
	switch e {
	case ApiKeyCreatedStatusActive:
		return true
	default:
		return false
	}
}

// Defines values for PlanPlanType.
const (
	PlanPlanTypeCoding PlanPlanType = "coding"
	PlanPlanTypeToken  PlanPlanType = "token"
)

// Valid indicates whether the value is a known member of the PlanPlanType enum.
func (e PlanPlanType) Valid() bool {
	switch e {
	case PlanPlanTypeCoding:
		return true
	case PlanPlanTypeToken:
		return true
	default:
		return false
	}
}

// Defines values for PlanStatus.
const (
	PlanStatusActive   PlanStatus = "active"
	PlanStatusDisabled PlanStatus = "disabled"
)

// Valid indicates whether the value is a known member of the PlanStatus enum.
func (e PlanStatus) Valid() bool {
	switch e {
	case PlanStatusActive:
		return true
	case PlanStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for RequestLogStatus.
const (
	RequestLogStatusError   RequestLogStatus = "error"
	RequestLogStatusSuccess RequestLogStatus = "success"
)

// Valid indicates whether the value is a known member of the RequestLogStatus enum.
func (e RequestLogStatus) Valid() bool {
	switch e {
	case RequestLogStatusError:
		return true
	case RequestLogStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for RequestLogDetailStatus.
const (
	RequestLogDetailStatusError   RequestLogDetailStatus = "error"
	RequestLogDetailStatusSuccess RequestLogDetailStatus = "success"
)

// Valid indicates whether the value is a known member of the RequestLogDetailStatus enum.
func (e RequestLogDetailStatus) Valid() bool {
	switch e {
	case RequestLogDetailStatusError:
		return true
	case RequestLogDetailStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for UserPlanStatus.
const (
	UserPlanStatusActive   UserPlanStatus = "active"
	UserPlanStatusDisabled UserPlanStatus = "disabled"
	UserPlanStatusExpired  UserPlanStatus = "expired"
)

// Valid indicates whether the value is a known member of the UserPlanStatus enum.
func (e UserPlanStatus) Valid() bool {
	switch e {
	case UserPlanStatusActive:
		return true
	case UserPlanStatusDisabled:
		return true
	case UserPlanStatusExpired:
		return true
	default:
		return false
	}
}

// Defines values for UserSettingsPreferredBilling.
const (
	UserSettingsPreferredBillingCoding UserSettingsPreferredBilling = "coding"
	UserSettingsPreferredBillingToken  UserSettingsPreferredBilling = "token"
)

// Valid indicates whether the value is a known member of the UserSettingsPreferredBilling enum.
func (e UserSettingsPreferredBilling) Valid() bool {
	switch e {
	case UserSettingsPreferredBillingCoding:
		return true
	case UserSettingsPreferredBillingToken:
		return true
	default:
		return false
	}
}

// Defines values for UserSettingsUpdatePreferredBilling.
const (
	UserSettingsUpdatePreferredBillingCoding UserSettingsUpdatePreferredBilling = "coding"
	UserSettingsUpdatePreferredBillingToken  UserSettingsUpdatePreferredBilling = "token"
)

// Valid indicates whether the value is a known member of the UserSettingsUpdatePreferredBilling enum.
func (e UserSettingsUpdatePreferredBilling) Valid() bool {
	switch e {
	case UserSettingsUpdatePreferredBillingCoding:
		return true
	case UserSettingsUpdatePreferredBillingToken:
		return true
	default:
		return false
	}
}

// Defines values for UpdateApiKeyJSONBodyStatus.
const (
	UpdateApiKeyJSONBodyStatusActive   UpdateApiKeyJSONBodyStatus = "active"
	UpdateApiKeyJSONBodyStatusDisabled UpdateApiKeyJSONBodyStatus = "disabled"
)

// Valid indicates whether the value is a known member of the UpdateApiKeyJSONBodyStatus enum.
func (e UpdateApiKeyJSONBodyStatus) Valid() bool {
	switch e {
	case UpdateApiKeyJSONBodyStatusActive:
		return true
	case UpdateApiKeyJSONBodyStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for ListRequestLogsParamsStatus.
const (
	ListRequestLogsParamsStatusAll     ListRequestLogsParamsStatus = "all"
	ListRequestLogsParamsStatusError   ListRequestLogsParamsStatus = "error"
	ListRequestLogsParamsStatusSuccess ListRequestLogsParamsStatus = "success"
)

// Valid indicates whether the value is a known member of the ListRequestLogsParamsStatus enum.
func (e ListRequestLogsParamsStatus) Valid() bool {
	switch e {
	case ListRequestLogsParamsStatusAll:
		return true
	case ListRequestLogsParamsStatusError:
		return true
	case ListRequestLogsParamsStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ApiGetHealthz200JSONResponseBodyStatus.
const (
	Ok ApiGetHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the ApiGetHealthz200JSONResponseBodyStatus enum.
func (e ApiGetHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time          `json:"createdAt"`
	ExpiresAt *time.Time         `json:"expiresAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`

	// KeyPrefix First 12 chars of key for identification
	KeyPrefix string `json:"keyPrefix"`

	// KeySuffix Last 8 chars of key for identification
	KeySuffix  string       `json:"keySuffix"`
	LastUsedAt *time.Time   `json:"lastUsedAt,omitempty"`
	Name       string       `json:"name"`
	Status     ApiKeyStatus `json:"status"`
}

// ApiKeyStatus defines model for ApiKey.Status.
type ApiKeyStatus string

// ApiKeyCreated defines model for ApiKeyCreated.
type ApiKeyCreated struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	KeyPrefix string             `json:"keyPrefix"`
	KeySuffix string             `json:"keySuffix"`
	Name      string             `json:"name"`

	// Secret Full API key secret — only returned on create/rotate
	Secret string              `json:"secret"`
	Status ApiKeyCreatedStatus `json:"status"`
}

// ApiKeyCreatedStatus defines model for ApiKeyCreated.Status.
type ApiKeyCreatedStatus string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    *string `json:"code,omitempty"`
		Message string  `json:"message"`
		Param   *string `json:"param,omitempty"`
		Type    string  `json:"type"`
	} `json:"error"`
}

// Plan defines model for Plan.
type Plan struct {
	AllowedModels *[]string          `json:"allowedModels,omitempty"`
	DurationDays  int                `json:"durationDays"`
	Id            openapi_types.UUID `json:"id"`
	Name          string             `json:"name"`
	PlanType      PlanPlanType       `json:"planType"`
	Price         float64            `json:"price"`
	Status        PlanStatus         `json:"status"`

	// TotalQuota Total quota as string (bigint)
	TotalQuota string `json:"totalQuota"`
}

// PlanPlanType defines model for Plan.PlanType.
type PlanPlanType string

// PlanStatus defines model for Plan.Status.
type PlanStatus string

// RequestLog defines model for RequestLog.
type RequestLog struct {
	// Cost Cost as string (bigint, in smallest unit)
	Cost         *string          `json:"cost,omitempty"`
	CreatedAt    time.Time        `json:"createdAt"`
	DurationMs   *int             `json:"durationMs,omitempty"`
	InputTokens  *int             `json:"inputTokens,omitempty"`
	Model        string           `json:"model"`
	OutputTokens *int             `json:"outputTokens,omitempty"`
	RequestId    string           `json:"requestId"`
	Status       RequestLogStatus `json:"status"`
}

// RequestLogStatus defines model for RequestLog.Status.
type RequestLogStatus string

// RequestLogDetail defines model for RequestLogDetail.
type RequestLogDetail struct {
	Attempts *[]struct {
		Attempt    *int       `json:"attempt,omitempty"`
		CreatedAt  *time.Time `json:"createdAt,omitempty"`
		DurationMs *int       `json:"durationMs,omitempty"`
		Model      *string    `json:"model,omitempty"`
		Provider   *string    `json:"provider,omitempty"`
		Status     *string    `json:"status,omitempty"`
	} `json:"attempts,omitempty"`
	Cost         *string                `json:"cost,omitempty"`
	CreatedAt    time.Time              `json:"createdAt"`
	DurationMs   *int                   `json:"durationMs,omitempty"`
	ErrorMessage *string                `json:"errorMessage,omitempty"`
	InputTokens  *int                   `json:"inputTokens,omitempty"`
	Model        string                 `json:"model"`
	OutputTokens *int                   `json:"outputTokens,omitempty"`
	Provider     *string                `json:"provider,omitempty"`
	RequestId    string                 `json:"requestId"`
	Status       RequestLogDetailStatus `json:"status"`
}

// RequestLogDetailStatus defines model for RequestLogDetail.Status.
type RequestLogDetailStatus string

// UsageStats defines model for UsageStats.
type UsageStats struct {
	ByModel *[]struct {
		Cost         *string `json:"cost,omitempty"`
		InputTokens  *string `json:"inputTokens,omitempty"`
		Model        *string `json:"model,omitempty"`
		OutputTokens *string `json:"outputTokens,omitempty"`
		Requests     *int    `json:"requests,omitempty"`
	} `json:"byModel,omitempty"`
	Days              int    `json:"days"`
	TotalCost         string `json:"totalCost"`
	TotalInputTokens  string `json:"totalInputTokens"`
	TotalOutputTokens string `json:"totalOutputTokens"`
	TotalRequests     int    `json:"totalRequests"`
}

// UserBalance defines model for UserBalance.
type UserBalance struct {
	// CodingRemaining Coding quota remaining (bigint string)
	CodingRemaining string `json:"codingRemaining"`

	// TokenRemaining Token quota remaining (bigint string)
	TokenRemaining string `json:"tokenRemaining"`
}

// UserPlan defines model for UserPlan.
type UserPlan struct {
	ActivatedAt    time.Time          `json:"activatedAt"`
	ExpiresAt      *time.Time         `json:"expiresAt,omitempty"`
	Id             openapi_types.UUID `json:"id"`
	PlanId         openapi_types.UUID `json:"planId"`
	PlanType       string             `json:"planType"`
	Priority       *int               `json:"priority,omitempty"`
	RemainingQuota string             `json:"remainingQuota"`
	Status         UserPlanStatus     `json:"status"`
	TotalQuota     string             `json:"totalQuota"`
}

// UserPlanStatus defines model for UserPlan.Status.
type UserPlanStatus string

// UserSettings defines model for UserSettings.
type UserSettings struct {
	FallbackEnabled  bool                         `json:"fallbackEnabled"`
	PreferredBilling UserSettingsPreferredBilling `json:"preferredBilling"`
}

// UserSettingsPreferredBilling defines model for UserSettings.PreferredBilling.
type UserSettingsPreferredBilling string

// UserSettingsUpdate defines model for UserSettingsUpdate.
type UserSettingsUpdate struct {
	FallbackEnabled  *bool                               `json:"fallbackEnabled,omitempty"`
	PreferredBilling *UserSettingsUpdatePreferredBilling `json:"preferredBilling,omitempty"`
}

// UserSettingsUpdatePreferredBilling defines model for UserSettingsUpdate.PreferredBilling.
type UserSettingsUpdatePreferredBilling string

// KeyId defines model for keyId.
type KeyId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateApiKeyJSONBody defines parameters for CreateApiKey.
type CreateApiKeyJSONBody struct {
	// ExpiresAt Optional expiration time
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Name Human-readable key name
	Name *string `json:"name,omitempty"`
}

// UpdateApiKeyJSONBody defines parameters for UpdateApiKey.
type UpdateApiKeyJSONBody struct {
	Name   *string                     `json:"name,omitempty"`
	Status *UpdateApiKeyJSONBodyStatus `json:"status,omitempty"`
}

// UpdateApiKeyJSONBodyStatus defines parameters for UpdateApiKey.
type UpdateApiKeyJSONBodyStatus string

// ListRequestLogsParams defines parameters for ListRequestLogs.
type ListRequestLogsParams struct {
	Page     *int `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// Model Filter by model ID
	Model     *string                      `form:"model,omitempty" json:"model,omitempty"`
	Status    *ListRequestLogsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	StartDate *time.Time                   `form:"startDate,omitempty" json:"startDate,omitempty"`
	EndDate   *time.Time                   `form:"endDate,omitempty" json:"endDate,omitempty"`
}

// ListRequestLogsParamsStatus defines parameters for ListRequestLogs.
type ListRequestLogsParamsStatus string

// GetRequestLogStatsParams defines parameters for GetRequestLogStats.
type GetRequestLogStatsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// ApiGetHealthz200JSONResponseBodyStatus defines parameters for ApiGetHealthz.
type ApiGetHealthz200JSONResponseBodyStatus string

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody CreateApiKeyJSONBody

// UpdateApiKeyJSONRequestBody defines body for UpdateApiKey for application/json ContentType.
type UpdateApiKeyJSONRequestBody UpdateApiKeyJSONBody

// UpdateUserSettingsJSONRequestBody defines body for UpdateUserSettings for application/json ContentType.
type UpdateUserSettingsJSONRequestBody = UserSettingsUpdate
