// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListApiKeys List user's API keys
	// (GET /api/v1/keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request)
	// CreateApiKey Create a new API key
	// (POST /api/v1/keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request)
	// DeleteApiKey Delete API key (soft delete)
	// (DELETE /api/v1/keys/{keyId})
	DeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// GetApiKey Get API key details
	// (GET /api/v1/keys/{keyId})
	GetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// UpdateApiKey Update API key
	// (PATCH /api/v1/keys/{keyId})
	UpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// RotateApiKey Rotate API key (generate new secret, keep metadata)
	// (POST /api/v1/keys/{keyId}/rotate)
	RotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId)
	// ListPlans List available plans
	// (GET /api/v1/plans)
	ListPlans(w http.ResponseWriter, r *http.Request)
	// ListRequestLogs List user's request logs
	// (GET /api/v1/request-logs)
	ListRequestLogs(w http.ResponseWriter, r *http.Request, params ListRequestLogsParams)
	// GetRequestLogStats Get user's usage statistics
	// (GET /api/v1/request-logs/stats)
	GetRequestLogStats(w http.ResponseWriter, r *http.Request, params GetRequestLogStatsParams)
	// GetRequestLog Get request log details
	// (GET /api/v1/request-logs/{requestId})
	GetRequestLog(w http.ResponseWriter, r *http.Request, requestId string)
	// GetUserBalance Get user's current balance
	// (GET /api/v1/user/balance)
	GetUserBalance(w http.ResponseWriter, r *http.Request)
	// ListUserPlans List user's active plan subscriptions
	// (GET /api/v1/user/plans)
	ListUserPlans(w http.ResponseWriter, r *http.Request)
	// GetUserSettings Get user settings
	// (GET /api/v1/user/settings)
	GetUserSettings(w http.ResponseWriter, r *http.Request)
	// UpdateUserSettings Update user settings
	// (PATCH /api/v1/user/settings)
	UpdateUserSettings(w http.ResponseWriter, r *http.Request)
	// ApiGetHealthz Health endpoint
	// (GET /healthz)
	ApiGetHealthz(w http.ResponseWriter, r *http.Request)
	// ApiHeadHealthz Health endpoint HEAD
	// (HEAD /healthz)
	ApiHeadHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListApiKeys List user's API keys
// (GET /api/v1/keys)
func (_ Unimplemented) ListApiKeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateApiKey Create a new API key
// (POST /api/v1/keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteApiKey Delete API key (soft delete)
// (DELETE /api/v1/keys/{keyId})
func (_ Unimplemented) DeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetApiKey Get API key details
// (GET /api/v1/keys/{keyId})
func (_ Unimplemented) GetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateApiKey Update API key
// (PATCH /api/v1/keys/{keyId})
func (_ Unimplemented) UpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RotateApiKey Rotate API key (generate new secret, keep metadata)
// (POST /api/v1/keys/{keyId}/rotate)
func (_ Unimplemented) RotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListPlans List available plans
// (GET /api/v1/plans)
func (_ Unimplemented) ListPlans(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListRequestLogs List user's request logs
// (GET /api/v1/request-logs)
func (_ Unimplemented) ListRequestLogs(w http.ResponseWriter, r *http.Request, params ListRequestLogsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRequestLogStats Get user's usage statistics
// (GET /api/v1/request-logs/stats)
func (_ Unimplemented) GetRequestLogStats(w http.ResponseWriter, r *http.Request, params GetRequestLogStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRequestLog Get request log details
// (GET /api/v1/request-logs/{requestId})
func (_ Unimplemented) GetRequestLog(w http.ResponseWriter, r *http.Request, requestId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserBalance Get user's current balance
// (GET /api/v1/user/balance)
func (_ Unimplemented) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListUserPlans List user's active plan subscriptions
// (GET /api/v1/user/plans)
func (_ Unimplemented) ListUserPlans(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetUserSettings Get user settings
// (GET /api/v1/user/settings)
func (_ Unimplemented) GetUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateUserSettings Update user settings
// (PATCH /api/v1/user/settings)
func (_ Unimplemented) UpdateUserSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApiGetHealthz Health endpoint
// (GET /healthz)
func (_ Unimplemented) ApiGetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ApiHeadHealthz Health endpoint HEAD
// (HEAD /healthz)
func (_ Unimplemented) ApiHeadHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiKey operation middleware
func (siw *ServerInterfaceWrapper) GetApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApiKey operation middleware
func (siw *ServerInterfaceWrapper) UpdateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateApiKey operation middleware
func (siw *ServerInterfaceWrapper) RotateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "keyId" -------------
	var keyId KeyId

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", chi.URLParam(r, "keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateApiKey(w, r, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlans operation middleware
func (siw *ServerInterfaceWrapper) ListPlans(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlans(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRequestLogs operation middleware
func (siw *ServerInterfaceWrapper) ListRequestLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRequestLogsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "pageSize"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "model" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "model", r.URL.Query(), &params.Model, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "model"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "model", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "startDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "startDate", r.URL.Query(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "startDate"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "startDate", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "endDate" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "endDate", r.URL.Query(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "endDate"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "endDate", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRequestLogs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRequestLogStats operation middleware
func (siw *ServerInterfaceWrapper) GetRequestLogStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRequestLogStatsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", r.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRequestLogStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRequestLog operation middleware
func (siw *ServerInterfaceWrapper) GetRequestLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "requestId" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", chi.URLParam(r, "requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRequestLog(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserBalance(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserBalance(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserPlans operation middleware
func (siw *ServerInterfaceWrapper) ListUserPlans(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserPlans(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserSettings operation middleware
func (siw *ServerInterfaceWrapper) GetUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApiGetHealthz operation middleware
func (siw *ServerInterfaceWrapper) ApiGetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApiGetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApiHeadHealthz operation middleware
func (siw *ServerInterfaceWrapper) ApiHeadHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApiHeadHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.ApiGetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/healthz", wrapper.ApiHeadHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/keys", wrapper.ListApiKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/keys/{keyId}", wrapper.DeleteApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/keys/{keyId}", wrapper.GetApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/keys/{keyId}", wrapper.UpdateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/keys/{keyId}/rotate", wrapper.RotateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/plans", wrapper.ListPlans)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/user/balance", wrapper.GetUserBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/user/plans", wrapper.ListUserPlans)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/request-logs", wrapper.ListRequestLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/request-logs/{requestId}", wrapper.GetRequestLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/request-logs/stats", wrapper.GetRequestLogStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/user/settings", wrapper.GetUserSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/user/settings", wrapper.UpdateUserSettings)
	})

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListApiKeysRequestObject struct {
}

type ListApiKeysResponseObject interface {
	VisitListApiKeysResponse(w http.ResponseWriter) error
}

type ListApiKeys200JSONResponse struct {
	Keys []ApiKey `json:"keys"`
}

func (response ListApiKeys200JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListApiKeys401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListApiKeys401JSONResponse) VisitListApiKeysResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKeyRequestObject struct {
	Body *CreateApiKeyJSONRequestBody
}

type CreateApiKeyResponseObject interface {
	VisitCreateApiKeyResponse(w http.ResponseWriter) error
}

type CreateApiKey201JSONResponse struct {
	Key ApiKeyCreated `json:"key"`
}

func (response CreateApiKey201JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateApiKey400JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateApiKey401JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type DeleteApiKeyResponseObject interface {
	VisitDeleteApiKeyResponse(w http.ResponseWriter) error
}

type DeleteApiKey204Response struct {
}

func (response DeleteApiKey204Response) VisitDeleteApiKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteApiKey401JSONResponse) VisitDeleteApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteApiKey404JSONResponse) VisitDeleteApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type GetApiKeyResponseObject interface {
	VisitGetApiKeyResponse(w http.ResponseWriter) error
}

type GetApiKey200JSONResponse struct {
	Key ApiKey `json:"key"`
}

func (response GetApiKey200JSONResponse) VisitGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetApiKey401JSONResponse) VisitGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response GetApiKey404JSONResponse) VisitGetApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
	Body  *UpdateApiKeyJSONRequestBody
}

type UpdateApiKeyResponseObject interface {
	VisitUpdateApiKeyResponse(w http.ResponseWriter) error
}

type UpdateApiKey200JSONResponse struct {
	Key ApiKey `json:"key"`
}

func (response UpdateApiKey200JSONResponse) VisitUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApiKey400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateApiKey400JSONResponse) VisitUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateApiKey401JSONResponse) VisitUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateApiKey404JSONResponse) VisitUpdateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RotateApiKeyRequestObject struct {
	KeyId KeyId `json:"keyId"`
}

type RotateApiKeyResponseObject interface {
	VisitRotateApiKeyResponse(w http.ResponseWriter) error
}

type RotateApiKey200JSONResponse struct {
	Key ApiKeyCreated `json:"key"`
}

func (response RotateApiKey200JSONResponse) VisitRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RotateApiKey401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RotateApiKey401JSONResponse) VisitRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RotateApiKey404JSONResponse struct{ NotFoundJSONResponse }

func (response RotateApiKey404JSONResponse) VisitRotateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlansRequestObject struct {
}

type ListPlansResponseObject interface {
	VisitListPlansResponse(w http.ResponseWriter) error
}

type ListPlans200JSONResponse struct {
	Plans []Plan `json:"plans"`
}

func (response ListPlans200JSONResponse) VisitListPlansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequestLogsRequestObject struct {
	Params ListRequestLogsParams
}

type ListRequestLogsResponseObject interface {
	VisitListRequestLogsResponse(w http.ResponseWriter) error
}

type ListRequestLogs200JSONResponse struct {
	Logs     []RequestLog `json:"logs"`
	Page     int          `json:"page"`
	PageSize int          `json:"pageSize"`
	Total    int          `json:"total"`
}

func (response ListRequestLogs200JSONResponse) VisitListRequestLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListRequestLogs401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListRequestLogs401JSONResponse) VisitListRequestLogsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLogStatsRequestObject struct {
	Params GetRequestLogStatsParams
}

type GetRequestLogStatsResponseObject interface {
	VisitGetRequestLogStatsResponse(w http.ResponseWriter) error
}

type GetRequestLogStats200JSONResponse UsageStats

func (response GetRequestLogStats200JSONResponse) VisitGetRequestLogStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLogStats401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRequestLogStats401JSONResponse) VisitGetRequestLogStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLogRequestObject struct {
	RequestId string `json:"requestId"`
}

type GetRequestLogResponseObject interface {
	VisitGetRequestLogResponse(w http.ResponseWriter) error
}

type GetRequestLog200JSONResponse RequestLogDetail

func (response GetRequestLog200JSONResponse) VisitGetRequestLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLog401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetRequestLog401JSONResponse) VisitGetRequestLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRequestLog404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRequestLog404JSONResponse) VisitGetRequestLogResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserBalanceRequestObject struct {
}

type GetUserBalanceResponseObject interface {
	VisitGetUserBalanceResponse(w http.ResponseWriter) error
}

type GetUserBalance200JSONResponse UserBalance

func (response GetUserBalance200JSONResponse) VisitGetUserBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserBalance401JSONResponse) VisitGetUserBalanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserPlansRequestObject struct {
}

type ListUserPlansResponseObject interface {
	VisitListUserPlansResponse(w http.ResponseWriter) error
}

type ListUserPlans200JSONResponse struct {
	Plans []UserPlan `json:"plans"`
}

func (response ListUserPlans200JSONResponse) VisitListUserPlansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListUserPlans401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListUserPlans401JSONResponse) VisitListUserPlansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserSettingsRequestObject struct {
}

type GetUserSettingsResponseObject interface {
	VisitGetUserSettingsResponse(w http.ResponseWriter) error
}

type GetUserSettings200JSONResponse UserSettings

func (response GetUserSettings200JSONResponse) VisitGetUserSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetUserSettings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserSettings401JSONResponse) VisitGetUserSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserSettingsRequestObject struct {
	Body *UpdateUserSettingsJSONRequestBody
}

type UpdateUserSettingsResponseObject interface {
	VisitUpdateUserSettingsResponse(w http.ResponseWriter) error
}

type UpdateUserSettings200JSONResponse UserSettings

func (response UpdateUserSettings200JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserSettings400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUserSettings400JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateUserSettings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUserSettings401JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ApiGetHealthzRequestObject struct {
}

type ApiGetHealthzResponseObject interface {
	VisitApiGetHealthzResponse(w http.ResponseWriter) error
}

type ApiGetHealthz200ResponseHeaders struct {
	CacheControl *string
}

type ApiGetHealthz200JSONResponse struct {
	Body struct {
		Status ApiGetHealthz200JSONResponseBodyStatus `json:"status"`
	}
	Headers ApiGetHealthz200ResponseHeaders
}

func (response ApiGetHealthz200JSONResponse) VisitApiGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApiHeadHealthzRequestObject struct {
}

type ApiHeadHealthzResponseObject interface {
	VisitApiHeadHealthzResponse(w http.ResponseWriter) error
}

type ApiHeadHealthz200ResponseHeaders struct {
	CacheControl *string
}

type ApiHeadHealthz200Response struct {
	Headers ApiHeadHealthz200ResponseHeaders
}

func (response ApiHeadHealthz200Response) VisitApiHeadHealthzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListApiKeys List user's API keys
	// (GET /api/v1/keys)
	ListApiKeys(ctx context.Context, request ListApiKeysRequestObject) (ListApiKeysResponseObject, error)
	// CreateApiKey Create a new API key
	// (POST /api/v1/keys)
	CreateApiKey(ctx context.Context, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error)
	// DeleteApiKey Delete API key (soft delete)
	// (DELETE /api/v1/keys/{keyId})
	DeleteApiKey(ctx context.Context, request DeleteApiKeyRequestObject) (DeleteApiKeyResponseObject, error)
	// GetApiKey Get API key details
	// (GET /api/v1/keys/{keyId})
	GetApiKey(ctx context.Context, request GetApiKeyRequestObject) (GetApiKeyResponseObject, error)
	// UpdateApiKey Update API key
	// (PATCH /api/v1/keys/{keyId})
	UpdateApiKey(ctx context.Context, request UpdateApiKeyRequestObject) (UpdateApiKeyResponseObject, error)
	// RotateApiKey Rotate API key (generate new secret, keep metadata)
	// (POST /api/v1/keys/{keyId}/rotate)
	RotateApiKey(ctx context.Context, request RotateApiKeyRequestObject) (RotateApiKeyResponseObject, error)
	// ListPlans List available plans
	// (GET /api/v1/plans)
	ListPlans(ctx context.Context, request ListPlansRequestObject) (ListPlansResponseObject, error)
	// ListRequestLogs List user's request logs
	// (GET /api/v1/request-logs)
	ListRequestLogs(ctx context.Context, request ListRequestLogsRequestObject) (ListRequestLogsResponseObject, error)
	// GetRequestLogStats Get user's usage statistics
	// (GET /api/v1/request-logs/stats)
	GetRequestLogStats(ctx context.Context, request GetRequestLogStatsRequestObject) (GetRequestLogStatsResponseObject, error)
	// GetRequestLog Get request log details
	// (GET /api/v1/request-logs/{requestId})
	GetRequestLog(ctx context.Context, request GetRequestLogRequestObject) (GetRequestLogResponseObject, error)
	// GetUserBalance Get user's current balance
	// (GET /api/v1/user/balance)
	GetUserBalance(ctx context.Context, request GetUserBalanceRequestObject) (GetUserBalanceResponseObject, error)
	// ListUserPlans List user's active plan subscriptions
	// (GET /api/v1/user/plans)
	ListUserPlans(ctx context.Context, request ListUserPlansRequestObject) (ListUserPlansResponseObject, error)
	// GetUserSettings Get user settings
	// (GET /api/v1/user/settings)
	GetUserSettings(ctx context.Context, request GetUserSettingsRequestObject) (GetUserSettingsResponseObject, error)
	// UpdateUserSettings Update user settings
	// (PATCH /api/v1/user/settings)
	UpdateUserSettings(ctx context.Context, request UpdateUserSettingsRequestObject) (UpdateUserSettingsResponseObject, error)
	// ApiGetHealthz Health endpoint
	// (GET /healthz)
	ApiGetHealthz(ctx context.Context, request ApiGetHealthzRequestObject) (ApiGetHealthzResponseObject, error)
	// ApiHeadHealthz Health endpoint HEAD
	// (HEAD /healthz)
	ApiHeadHealthz(ctx context.Context, request ApiHeadHealthzRequestObject) (ApiHeadHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListApiKeys operation middleware
func (sh *strictHandler) ListApiKeys(w http.ResponseWriter, r *http.Request) {
	var request ListApiKeysRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListApiKeys(ctx, request.(ListApiKeysRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListApiKeys")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListApiKeysResponseObject); ok {
		if err := validResponse.VisitListApiKeysResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateApiKey operation middleware
func (sh *strictHandler) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	var request CreateApiKeyRequestObject

	var body CreateApiKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApiKey(ctx, request.(CreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateApiKeyResponseObject); ok {
		if err := validResponse.VisitCreateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiKey operation middleware
func (sh *strictHandler) DeleteApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request DeleteApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiKey(ctx, request.(DeleteApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiKeyResponseObject); ok {
		if err := validResponse.VisitDeleteApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiKey operation middleware
func (sh *strictHandler) GetApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request GetApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiKey(ctx, request.(GetApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiKeyResponseObject); ok {
		if err := validResponse.VisitGetApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateApiKey operation middleware
func (sh *strictHandler) UpdateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request UpdateApiKeyRequestObject

	request.KeyId = keyId

	var body UpdateApiKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateApiKey(ctx, request.(UpdateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateApiKeyResponseObject); ok {
		if err := validResponse.VisitUpdateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RotateApiKey operation middleware
func (sh *strictHandler) RotateApiKey(w http.ResponseWriter, r *http.Request, keyId KeyId) {
	var request RotateApiKeyRequestObject

	request.KeyId = keyId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RotateApiKey(ctx, request.(RotateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RotateApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RotateApiKeyResponseObject); ok {
		if err := validResponse.VisitRotateApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlans operation middleware
func (sh *strictHandler) ListPlans(w http.ResponseWriter, r *http.Request) {
	var request ListPlansRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlans(ctx, request.(ListPlansRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlans")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlansResponseObject); ok {
		if err := validResponse.VisitListPlansResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRequestLogs operation middleware
func (sh *strictHandler) ListRequestLogs(w http.ResponseWriter, r *http.Request, params ListRequestLogsParams) {
	var request ListRequestLogsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRequestLogs(ctx, request.(ListRequestLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRequestLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRequestLogsResponseObject); ok {
		if err := validResponse.VisitListRequestLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRequestLogStats operation middleware
func (sh *strictHandler) GetRequestLogStats(w http.ResponseWriter, r *http.Request, params GetRequestLogStatsParams) {
	var request GetRequestLogStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRequestLogStats(ctx, request.(GetRequestLogStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRequestLogStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRequestLogStatsResponseObject); ok {
		if err := validResponse.VisitGetRequestLogStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRequestLog operation middleware
func (sh *strictHandler) GetRequestLog(w http.ResponseWriter, r *http.Request, requestId string) {
	var request GetRequestLogRequestObject

	request.RequestId = requestId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRequestLog(ctx, request.(GetRequestLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRequestLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRequestLogResponseObject); ok {
		if err := validResponse.VisitGetRequestLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserBalance operation middleware
func (sh *strictHandler) GetUserBalance(w http.ResponseWriter, r *http.Request) {
	var request GetUserBalanceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserBalance(ctx, request.(GetUserBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserBalance")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserBalanceResponseObject); ok {
		if err := validResponse.VisitGetUserBalanceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListUserPlans operation middleware
func (sh *strictHandler) ListUserPlans(w http.ResponseWriter, r *http.Request) {
	var request ListUserPlansRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUserPlans(ctx, request.(ListUserPlansRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUserPlans")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUserPlansResponseObject); ok {
		if err := validResponse.VisitListUserPlansResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetUserSettings operation middleware
func (sh *strictHandler) GetUserSettings(w http.ResponseWriter, r *http.Request) {
	var request GetUserSettingsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserSettings(ctx, request.(GetUserSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetUserSettingsResponseObject); ok {
		if err := validResponse.VisitGetUserSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateUserSettings operation middleware
func (sh *strictHandler) UpdateUserSettings(w http.ResponseWriter, r *http.Request) {
	var request UpdateUserSettingsRequestObject

	var body UpdateUserSettingsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserSettings(ctx, request.(UpdateUserSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserSettings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateUserSettingsResponseObject); ok {
		if err := validResponse.VisitUpdateUserSettingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApiGetHealthz operation middleware
func (sh *strictHandler) ApiGetHealthz(w http.ResponseWriter, r *http.Request) {
	var request ApiGetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApiGetHealthz(ctx, request.(ApiGetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApiGetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApiGetHealthzResponseObject); ok {
		if err := validResponse.VisitApiGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApiHeadHealthz operation middleware
func (sh *strictHandler) ApiHeadHealthz(w http.ResponseWriter, r *http.Request) {
	var request ApiHeadHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApiHeadHealthz(ctx, request.(ApiHeadHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApiHeadHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApiHeadHealthzResponseObject); ok {
		if err := validResponse.VisitApiHeadHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
