// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/executor/v1.yaml (models).
// DO NOT EDIT. Regenerate via: packages/contracts/go/generate-executor.sh

// Package executorv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package executorv1

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AnthropicContentBlockCacheControlType.
const (
	AnthropicContentBlockCacheControlTypeEphemeral AnthropicContentBlockCacheControlType = "ephemeral"
)

// Valid indicates whether the value is a known member of the AnthropicContentBlockCacheControlType enum.
func (e AnthropicContentBlockCacheControlType) Valid() bool {
	switch e {
	case AnthropicContentBlockCacheControlTypeEphemeral:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicContentBlockSourceMediaType.
const (
	Imagegif  AnthropicContentBlockSourceMediaType = "image/gif"
	Imagejpeg AnthropicContentBlockSourceMediaType = "image/jpeg"
	Imagepng  AnthropicContentBlockSourceMediaType = "image/png"
	Imagewebp AnthropicContentBlockSourceMediaType = "image/webp"
)

// Valid indicates whether the value is a known member of the AnthropicContentBlockSourceMediaType enum.
func (e AnthropicContentBlockSourceMediaType) Valid() bool {
	switch e {
	case Imagegif:
		return true
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicContentBlockSourceType.
const (
	Base64 AnthropicContentBlockSourceType = "base64"
)

// Valid indicates whether the value is a known member of the AnthropicContentBlockSourceType enum.
func (e AnthropicContentBlockSourceType) Valid() bool {
	switch e {
	case Base64:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicContentBlockType.
const (
	AnthropicContentBlockTypeImage      AnthropicContentBlockType = "image"
	AnthropicContentBlockTypeText       AnthropicContentBlockType = "text"
	AnthropicContentBlockTypeThinking   AnthropicContentBlockType = "thinking"
	AnthropicContentBlockTypeToolResult AnthropicContentBlockType = "tool_result"
	AnthropicContentBlockTypeToolUse    AnthropicContentBlockType = "tool_use"
)

// Valid indicates whether the value is a known member of the AnthropicContentBlockType enum.
func (e AnthropicContentBlockType) Valid() bool {
	switch e {
	case AnthropicContentBlockTypeImage:
		return true
	case AnthropicContentBlockTypeText:
		return true
	case AnthropicContentBlockTypeThinking:
		return true
	case AnthropicContentBlockTypeToolResult:
		return true
	case AnthropicContentBlockTypeToolUse:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicErrorResponseErrorType.
const (
	AnthropicErrorResponseErrorTypeApiError            AnthropicErrorResponseErrorType = "api_error"
	AnthropicErrorResponseErrorTypeAuthenticationError AnthropicErrorResponseErrorType = "authentication_error"
	AnthropicErrorResponseErrorTypeBillingError        AnthropicErrorResponseErrorType = "billing_error"
	AnthropicErrorResponseErrorTypeInvalidRequestError AnthropicErrorResponseErrorType = "invalid_request_error"
	AnthropicErrorResponseErrorTypeNotFoundError       AnthropicErrorResponseErrorType = "not_found_error"
	AnthropicErrorResponseErrorTypeOverloadedError     AnthropicErrorResponseErrorType = "overloaded_error"
	AnthropicErrorResponseErrorTypePermissionError     AnthropicErrorResponseErrorType = "permission_error"
	AnthropicErrorResponseErrorTypeRateLimitError      AnthropicErrorResponseErrorType = "rate_limit_error"
	AnthropicErrorResponseErrorTypeTimeoutError        AnthropicErrorResponseErrorType = "timeout_error"
)

// Valid indicates whether the value is a known member of the AnthropicErrorResponseErrorType enum.
func (e AnthropicErrorResponseErrorType) Valid() bool {
	switch e {
	case AnthropicErrorResponseErrorTypeApiError:
		return true
	case AnthropicErrorResponseErrorTypeAuthenticationError:
		return true
	case AnthropicErrorResponseErrorTypeBillingError:
		return true
	case AnthropicErrorResponseErrorTypeInvalidRequestError:
		return true
	case AnthropicErrorResponseErrorTypeNotFoundError:
		return true
	case AnthropicErrorResponseErrorTypeOverloadedError:
		return true
	case AnthropicErrorResponseErrorTypePermissionError:
		return true
	case AnthropicErrorResponseErrorTypeRateLimitError:
		return true
	case AnthropicErrorResponseErrorTypeTimeoutError:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicErrorResponseType.
const (
	Error AnthropicErrorResponseType = "error"
)

// Valid indicates whether the value is a known member of the AnthropicErrorResponseType enum.
func (e AnthropicErrorResponseType) Valid() bool {
	switch e {
	case Error:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicMessageRole.
const (
	AnthropicMessageRoleAssistant AnthropicMessageRole = "assistant"
	AnthropicMessageRoleUser      AnthropicMessageRole = "user"
)

// Valid indicates whether the value is a known member of the AnthropicMessageRole enum.
func (e AnthropicMessageRole) Valid() bool {
	switch e {
	case AnthropicMessageRoleAssistant:
		return true
	case AnthropicMessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicResponseContentBlockType.
const (
	AnthropicResponseContentBlockTypeText     AnthropicResponseContentBlockType = "text"
	AnthropicResponseContentBlockTypeThinking AnthropicResponseContentBlockType = "thinking"
	AnthropicResponseContentBlockTypeToolUse  AnthropicResponseContentBlockType = "tool_use"
)

// Valid indicates whether the value is a known member of the AnthropicResponseContentBlockType enum.
func (e AnthropicResponseContentBlockType) Valid() bool {
	switch e {
	case AnthropicResponseContentBlockTypeText:
		return true
	case AnthropicResponseContentBlockTypeThinking:
		return true
	case AnthropicResponseContentBlockTypeToolUse:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicSystemBlockCacheControlType.
const (
	AnthropicSystemBlockCacheControlTypeEphemeral AnthropicSystemBlockCacheControlType = "ephemeral"
)

// Valid indicates whether the value is a known member of the AnthropicSystemBlockCacheControlType enum.
func (e AnthropicSystemBlockCacheControlType) Valid() bool {
	switch e {
	case AnthropicSystemBlockCacheControlTypeEphemeral:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicSystemBlockType.
const (
	AnthropicSystemBlockTypeText AnthropicSystemBlockType = "text"
)

// Valid indicates whether the value is a known member of the AnthropicSystemBlockType enum.
func (e AnthropicSystemBlockType) Valid() bool {
	switch e {
	case AnthropicSystemBlockTypeText:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicToolCacheControlType.
const (
	AnthropicToolCacheControlTypeEphemeral AnthropicToolCacheControlType = "ephemeral"
)

// Valid indicates whether the value is a known member of the AnthropicToolCacheControlType enum.
func (e AnthropicToolCacheControlType) Valid() bool {
	switch e {
	case AnthropicToolCacheControlTypeEphemeral:
		return true
	default:
		return false
	}
}

// Defines values for AnthropicToolChoiceType.
const (
	AnthropicToolChoiceTypeAny  AnthropicToolChoiceType = "any"
	AnthropicToolChoiceTypeAuto AnthropicToolChoiceType = "auto"
	AnthropicToolChoiceTypeTool AnthropicToolChoiceType = "tool"
)

// Valid indicates whether the value is a known member of the AnthropicToolChoiceType enum.
func (e AnthropicToolChoiceType) Valid() bool {
	switch e {
	case AnthropicToolChoiceTypeAny:
		return true
	case AnthropicToolChoiceTypeAuto:
		return true
	case AnthropicToolChoiceTypeTool:
		return true
	default:
		return false
	}
}

// Defines values for ChatCompletionChoiceFinishReason.
const (
	ContentFilter ChatCompletionChoiceFinishReason = "content_filter"
	Length        ChatCompletionChoiceFinishReason = "length"
	Stop          ChatCompletionChoiceFinishReason = "stop"
	ToolCalls     ChatCompletionChoiceFinishReason = "tool_calls"
)

// Valid indicates whether the value is a known member of the ChatCompletionChoiceFinishReason enum.
func (e ChatCompletionChoiceFinishReason) Valid() bool {
	switch e {
	case ContentFilter:
		return true
	case Length:
		return true
	case Stop:
		return true
	case ToolCalls:
		return true
	default:
		return false
	}
}

// Defines values for ChatCompletionResponseObject.
const (
	ChatCompletion ChatCompletionResponseObject = "chat.completion"
)

// Valid indicates whether the value is a known member of the ChatCompletionResponseObject enum.
func (e ChatCompletionResponseObject) Valid() bool {
	switch e {
	case ChatCompletion:
		return true
	default:
		return false
	}
}

// Defines values for ChatContentPartImageUrlDetail.
const (
	ChatContentPartImageUrlDetailAuto ChatContentPartImageUrlDetail = "auto"
	ChatContentPartImageUrlDetailHigh ChatContentPartImageUrlDetail = "high"
	ChatContentPartImageUrlDetailLow  ChatContentPartImageUrlDetail = "low"
)

// Valid indicates whether the value is a known member of the ChatContentPartImageUrlDetail enum.
func (e ChatContentPartImageUrlDetail) Valid() bool {
	switch e {
	case ChatContentPartImageUrlDetailAuto:
		return true
	case ChatContentPartImageUrlDetailHigh:
		return true
	case ChatContentPartImageUrlDetailLow:
		return true
	default:
		return false
	}
}

// Defines values for ChatContentPartType.
const (
	ChatContentPartTypeImageUrl ChatContentPartType = "image_url"
	ChatContentPartTypeText     ChatContentPartType = "text"
)

// Valid indicates whether the value is a known member of the ChatContentPartType enum.
func (e ChatContentPartType) Valid() bool {
	switch e {
	case ChatContentPartTypeImageUrl:
		return true
	case ChatContentPartTypeText:
		return true
	default:
		return false
	}
}

// Defines values for ChatMessageRole.
const (
	ChatMessageRoleAssistant ChatMessageRole = "assistant"
	ChatMessageRoleSystem    ChatMessageRole = "system"
	ChatMessageRoleTool      ChatMessageRole = "tool"
	ChatMessageRoleUser      ChatMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatMessageRole enum.
func (e ChatMessageRole) Valid() bool {
	switch e {
	case ChatMessageRoleAssistant:
		return true
	case ChatMessageRoleSystem:
		return true
	case ChatMessageRoleTool:
		return true
	case ChatMessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for ChatRequestContentPartImageUrlDetail.
const (
	ChatRequestContentPartImageUrlDetailAuto ChatRequestContentPartImageUrlDetail = "auto"
	ChatRequestContentPartImageUrlDetailHigh ChatRequestContentPartImageUrlDetail = "high"
	ChatRequestContentPartImageUrlDetailLow  ChatRequestContentPartImageUrlDetail = "low"
)

// Valid indicates whether the value is a known member of the ChatRequestContentPartImageUrlDetail enum.
func (e ChatRequestContentPartImageUrlDetail) Valid() bool {
	switch e {
	case ChatRequestContentPartImageUrlDetailAuto:
		return true
	case ChatRequestContentPartImageUrlDetailHigh:
		return true
	case ChatRequestContentPartImageUrlDetailLow:
		return true
	default:
		return false
	}
}

// Defines values for ChatRequestContentPartType.
const (
	ChatRequestContentPartTypeImageUrl ChatRequestContentPartType = "image_url"
	ChatRequestContentPartTypeText     ChatRequestContentPartType = "text"
)

// Valid indicates whether the value is a known member of the ChatRequestContentPartType enum.
func (e ChatRequestContentPartType) Valid() bool {
	switch e {
	case ChatRequestContentPartTypeImageUrl:
		return true
	case ChatRequestContentPartTypeText:
		return true
	default:
		return false
	}
}

// Defines values for ChatRequestMessageRole.
const (
	ChatRequestMessageRoleAssistant ChatRequestMessageRole = "assistant"
	ChatRequestMessageRoleSystem    ChatRequestMessageRole = "system"
	ChatRequestMessageRoleTool      ChatRequestMessageRole = "tool"
	ChatRequestMessageRoleUser      ChatRequestMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatRequestMessageRole enum.
func (e ChatRequestMessageRole) Valid() bool {
	switch e {
	case ChatRequestMessageRoleAssistant:
		return true
	case ChatRequestMessageRoleSystem:
		return true
	case ChatRequestMessageRoleTool:
		return true
	case ChatRequestMessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for ChatRequestToolCallType.
const (
	ChatRequestToolCallTypeFunction ChatRequestToolCallType = "function"
)

// Valid indicates whether the value is a known member of the ChatRequestToolCallType enum.
func (e ChatRequestToolCallType) Valid() bool {
	switch e {
	case ChatRequestToolCallTypeFunction:
		return true
	default:
		return false
	}
}

// Defines values for ChatToolType.
const (
	ChatToolTypeFunction ChatToolType = "function"
)

// Valid indicates whether the value is a known member of the ChatToolType enum.
func (e ChatToolType) Valid() bool {
	switch e {
	case ChatToolTypeFunction:
		return true
	default:
		return false
	}
}

// Defines values for ChatToolCallType.
const (
	ChatToolCallTypeFunction ChatToolCallType = "function"
)

// Valid indicates whether the value is a known member of the ChatToolCallType enum.
func (e ChatToolCallType) Valid() bool {
	switch e {
	case ChatToolCallTypeFunction:
		return true
	default:
		return false
	}
}

// Defines values for ChatToolChoiceType.
const (
	ChatToolChoiceTypeFunction ChatToolChoiceType = "function"
)

// Valid indicates whether the value is a known member of the ChatToolChoiceType enum.
func (e ChatToolChoiceType) Valid() bool {
	switch e {
	case ChatToolChoiceTypeFunction:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatCompletionRequestReasoningEffort.
const (
	CreateChatCompletionRequestReasoningEffortHigh    CreateChatCompletionRequestReasoningEffort = "high"
	CreateChatCompletionRequestReasoningEffortLow     CreateChatCompletionRequestReasoningEffort = "low"
	CreateChatCompletionRequestReasoningEffortMax     CreateChatCompletionRequestReasoningEffort = "max"
	CreateChatCompletionRequestReasoningEffortMedium  CreateChatCompletionRequestReasoningEffort = "medium"
	CreateChatCompletionRequestReasoningEffortMinimal CreateChatCompletionRequestReasoningEffort = "minimal"
	CreateChatCompletionRequestReasoningEffortNone    CreateChatCompletionRequestReasoningEffort = "none"
	CreateChatCompletionRequestReasoningEffortXhigh   CreateChatCompletionRequestReasoningEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the CreateChatCompletionRequestReasoningEffort enum.
func (e CreateChatCompletionRequestReasoningEffort) Valid() bool {
	switch e {
	case CreateChatCompletionRequestReasoningEffortHigh:
		return true
	case CreateChatCompletionRequestReasoningEffortLow:
		return true
	case CreateChatCompletionRequestReasoningEffortMax:
		return true
	case CreateChatCompletionRequestReasoningEffortMedium:
		return true
	case CreateChatCompletionRequestReasoningEffortMinimal:
		return true
	case CreateChatCompletionRequestReasoningEffortNone:
		return true
	case CreateChatCompletionRequestReasoningEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatCompletionRequestResponseFormatType.
const (
	CreateChatCompletionRequestResponseFormatTypeJsonObject CreateChatCompletionRequestResponseFormatType = "json_object"
	CreateChatCompletionRequestResponseFormatTypeJsonSchema CreateChatCompletionRequestResponseFormatType = "json_schema"
	CreateChatCompletionRequestResponseFormatTypeText       CreateChatCompletionRequestResponseFormatType = "text"
)

// Valid indicates whether the value is a known member of the CreateChatCompletionRequestResponseFormatType enum.
func (e CreateChatCompletionRequestResponseFormatType) Valid() bool {
	switch e {
	case CreateChatCompletionRequestResponseFormatTypeJsonObject:
		return true
	case CreateChatCompletionRequestResponseFormatTypeJsonSchema:
		return true
	case CreateChatCompletionRequestResponseFormatTypeText:
		return true
	default:
		return false
	}
}

// Defines values for CreateChatCompletionRequestToolChoice0.
const (
	CreateChatCompletionRequestToolChoice0Auto     CreateChatCompletionRequestToolChoice0 = "auto"
	CreateChatCompletionRequestToolChoice0None     CreateChatCompletionRequestToolChoice0 = "none"
	CreateChatCompletionRequestToolChoice0Required CreateChatCompletionRequestToolChoice0 = "required"
)

// Valid indicates whether the value is a known member of the CreateChatCompletionRequestToolChoice0 enum.
func (e CreateChatCompletionRequestToolChoice0) Valid() bool {
	switch e {
	case CreateChatCompletionRequestToolChoice0Auto:
		return true
	case CreateChatCompletionRequestToolChoice0None:
		return true
	case CreateChatCompletionRequestToolChoice0Required:
		return true
	default:
		return false
	}
}

// Defines values for CreateImageRequestQuality.
const (
	Hd       CreateImageRequestQuality = "hd"
	Standard CreateImageRequestQuality = "standard"
)

// Valid indicates whether the value is a known member of the CreateImageRequestQuality enum.
func (e CreateImageRequestQuality) Valid() bool {
	switch e {
	case Hd:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// Defines values for CreateImageRequestResponseFormat.
const (
	B64Json CreateImageRequestResponseFormat = "b64_json"
	Url     CreateImageRequestResponseFormat = "url"
)

// Valid indicates whether the value is a known member of the CreateImageRequestResponseFormat enum.
func (e CreateImageRequestResponseFormat) Valid() bool {
	switch e {
	case B64Json:
		return true
	case Url:
		return true
	default:
		return false
	}
}

// Defines values for CreateImageRequestSize.
const (
	N1024x1024 CreateImageRequestSize = "1024x1024"
	N1024x1792 CreateImageRequestSize = "1024x1792"
	N1792x1024 CreateImageRequestSize = "1792x1024"
	N256x256   CreateImageRequestSize = "256x256"
	N512x512   CreateImageRequestSize = "512x512"
)

// Valid indicates whether the value is a known member of the CreateImageRequestSize enum.
func (e CreateImageRequestSize) Valid() bool {
	switch e {
	case N1024x1024:
		return true
	case N1024x1792:
		return true
	case N1792x1024:
		return true
	case N256x256:
		return true
	case N512x512:
		return true
	default:
		return false
	}
}

// Defines values for CreateImageRequestStyle.
const (
	Natural CreateImageRequestStyle = "natural"
	Vivid   CreateImageRequestStyle = "vivid"
)

// Valid indicates whether the value is a known member of the CreateImageRequestStyle enum.
func (e CreateImageRequestStyle) Valid() bool {
	switch e {
	case Natural:
		return true
	case Vivid:
		return true
	default:
		return false
	}
}

// Defines values for CreateMessageResponseRole.
const (
	CreateMessageResponseRoleAssistant CreateMessageResponseRole = "assistant"
)

// Valid indicates whether the value is a known member of the CreateMessageResponseRole enum.
func (e CreateMessageResponseRole) Valid() bool {
	switch e {
	case CreateMessageResponseRoleAssistant:
		return true
	default:
		return false
	}
}

// Defines values for CreateMessageResponseStopReason.
const (
	CreateMessageResponseStopReasonEndTurn      CreateMessageResponseStopReason = "end_turn"
	CreateMessageResponseStopReasonMaxTokens    CreateMessageResponseStopReason = "max_tokens"
	CreateMessageResponseStopReasonStopSequence CreateMessageResponseStopReason = "stop_sequence"
	CreateMessageResponseStopReasonToolUse      CreateMessageResponseStopReason = "tool_use"
)

// Valid indicates whether the value is a known member of the CreateMessageResponseStopReason enum.
func (e CreateMessageResponseStopReason) Valid() bool {
	switch e {
	case CreateMessageResponseStopReasonEndTurn:
		return true
	case CreateMessageResponseStopReasonMaxTokens:
		return true
	case CreateMessageResponseStopReasonStopSequence:
		return true
	case CreateMessageResponseStopReasonToolUse:
		return true
	default:
		return false
	}
}

// Defines values for CreateMessageResponseType.
const (
	CreateMessageResponseTypeMessage CreateMessageResponseType = "message"
)

// Valid indicates whether the value is a known member of the CreateMessageResponseType enum.
func (e CreateMessageResponseType) Valid() bool {
	switch e {
	case CreateMessageResponseTypeMessage:
		return true
	default:
		return false
	}
}

// Defines values for CreateResponseRequestTextFormatType.
const (
	CreateResponseRequestTextFormatTypeJsonObject CreateResponseRequestTextFormatType = "json_object"
	CreateResponseRequestTextFormatTypeJsonSchema CreateResponseRequestTextFormatType = "json_schema"
	CreateResponseRequestTextFormatTypeText       CreateResponseRequestTextFormatType = "text"
)

// Valid indicates whether the value is a known member of the CreateResponseRequestTextFormatType enum.
func (e CreateResponseRequestTextFormatType) Valid() bool {
	switch e {
	case CreateResponseRequestTextFormatTypeJsonObject:
		return true
	case CreateResponseRequestTextFormatTypeJsonSchema:
		return true
	case CreateResponseRequestTextFormatTypeText:
		return true
	default:
		return false
	}
}

// Defines values for CreateResponseRequestToolChoice.
const (
	CreateResponseRequestToolChoiceAuto     CreateResponseRequestToolChoice = "auto"
	CreateResponseRequestToolChoiceNone     CreateResponseRequestToolChoice = "none"
	CreateResponseRequestToolChoiceRequired CreateResponseRequestToolChoice = "required"
)

// Valid indicates whether the value is a known member of the CreateResponseRequestToolChoice enum.
func (e CreateResponseRequestToolChoice) Valid() bool {
	switch e {
	case CreateResponseRequestToolChoiceAuto:
		return true
	case CreateResponseRequestToolChoiceNone:
		return true
	case CreateResponseRequestToolChoiceRequired:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ModelListResponseObject.
const (
	List ModelListResponseObject = "list"
)

// Valid indicates whether the value is a known member of the ModelListResponseObject enum.
func (e ModelListResponseObject) Valid() bool {
	switch e {
	case List:
		return true
	default:
		return false
	}
}

// Defines values for ModelObjectCapabilities.
const (
	ModelObjectCapabilitiesFunctionCalling ModelObjectCapabilities = "function_calling"
	ModelObjectCapabilitiesImage           ModelObjectCapabilities = "image"
	ModelObjectCapabilitiesJsonMode        ModelObjectCapabilities = "json_mode"
	ModelObjectCapabilitiesLongContext     ModelObjectCapabilities = "long_context"
	ModelObjectCapabilitiesText            ModelObjectCapabilities = "text"
	ModelObjectCapabilitiesThinking        ModelObjectCapabilities = "thinking"
	ModelObjectCapabilitiesVision          ModelObjectCapabilities = "vision"
)

// Valid indicates whether the value is a known member of the ModelObjectCapabilities enum.
func (e ModelObjectCapabilities) Valid() bool {
	switch e {
	case ModelObjectCapabilitiesFunctionCalling:
		return true
	case ModelObjectCapabilitiesImage:
		return true
	case ModelObjectCapabilitiesJsonMode:
		return true
	case ModelObjectCapabilitiesLongContext:
		return true
	case ModelObjectCapabilitiesText:
		return true
	case ModelObjectCapabilitiesThinking:
		return true
	case ModelObjectCapabilitiesVision:
		return true
	default:
		return false
	}
}

// Defines values for ModelObjectObject.
const (
	Model ModelObjectObject = "model"
)

// Valid indicates whether the value is a known member of the ModelObjectObject enum.
func (e ModelObjectObject) Valid() bool {
	switch e {
	case Model:
		return true
	default:
		return false
	}
}

// Defines values for ModelThinkingConfigDefaultEffort.
const (
	ModelThinkingConfigDefaultEffortHigh    ModelThinkingConfigDefaultEffort = "high"
	ModelThinkingConfigDefaultEffortLow     ModelThinkingConfigDefaultEffort = "low"
	ModelThinkingConfigDefaultEffortMax     ModelThinkingConfigDefaultEffort = "max"
	ModelThinkingConfigDefaultEffortMedium  ModelThinkingConfigDefaultEffort = "medium"
	ModelThinkingConfigDefaultEffortMinimal ModelThinkingConfigDefaultEffort = "minimal"
	ModelThinkingConfigDefaultEffortNone    ModelThinkingConfigDefaultEffort = "none"
	ModelThinkingConfigDefaultEffortXhigh   ModelThinkingConfigDefaultEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the ModelThinkingConfigDefaultEffort enum.
func (e ModelThinkingConfigDefaultEffort) Valid() bool {
	switch e {
	case ModelThinkingConfigDefaultEffortHigh:
		return true
	case ModelThinkingConfigDefaultEffortLow:
		return true
	case ModelThinkingConfigDefaultEffortMax:
		return true
	case ModelThinkingConfigDefaultEffortMedium:
		return true
	case ModelThinkingConfigDefaultEffortMinimal:
		return true
	case ModelThinkingConfigDefaultEffortNone:
		return true
	case ModelThinkingConfigDefaultEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for ModelThinkingConfigEffortLevels.
const (
	ModelThinkingConfigEffortLevelsHigh    ModelThinkingConfigEffortLevels = "high"
	ModelThinkingConfigEffortLevelsLow     ModelThinkingConfigEffortLevels = "low"
	ModelThinkingConfigEffortLevelsMax     ModelThinkingConfigEffortLevels = "max"
	ModelThinkingConfigEffortLevelsMedium  ModelThinkingConfigEffortLevels = "medium"
	ModelThinkingConfigEffortLevelsMinimal ModelThinkingConfigEffortLevels = "minimal"
	ModelThinkingConfigEffortLevelsNone    ModelThinkingConfigEffortLevels = "none"
	ModelThinkingConfigEffortLevelsXhigh   ModelThinkingConfigEffortLevels = "xhigh"
)

// Valid indicates whether the value is a known member of the ModelThinkingConfigEffortLevels enum.
func (e ModelThinkingConfigEffortLevels) Valid() bool {
	switch e {
	case ModelThinkingConfigEffortLevelsHigh:
		return true
	case ModelThinkingConfigEffortLevelsLow:
		return true
	case ModelThinkingConfigEffortLevelsMax:
		return true
	case ModelThinkingConfigEffortLevelsMedium:
		return true
	case ModelThinkingConfigEffortLevelsMinimal:
		return true
	case ModelThinkingConfigEffortLevelsNone:
		return true
	case ModelThinkingConfigEffortLevelsXhigh:
		return true
	default:
		return false
	}
}

// Defines values for ModelThinkingConfigMaxEffort.
const (
	ModelThinkingConfigMaxEffortHigh    ModelThinkingConfigMaxEffort = "high"
	ModelThinkingConfigMaxEffortLow     ModelThinkingConfigMaxEffort = "low"
	ModelThinkingConfigMaxEffortMax     ModelThinkingConfigMaxEffort = "max"
	ModelThinkingConfigMaxEffortMedium  ModelThinkingConfigMaxEffort = "medium"
	ModelThinkingConfigMaxEffortMinimal ModelThinkingConfigMaxEffort = "minimal"
	ModelThinkingConfigMaxEffortNone    ModelThinkingConfigMaxEffort = "none"
	ModelThinkingConfigMaxEffortXhigh   ModelThinkingConfigMaxEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the ModelThinkingConfigMaxEffort enum.
func (e ModelThinkingConfigMaxEffort) Valid() bool {
	switch e {
	case ModelThinkingConfigMaxEffortHigh:
		return true
	case ModelThinkingConfigMaxEffortLow:
		return true
	case ModelThinkingConfigMaxEffortMax:
		return true
	case ModelThinkingConfigMaxEffortMedium:
		return true
	case ModelThinkingConfigMaxEffortMinimal:
		return true
	case ModelThinkingConfigMaxEffortNone:
		return true
	case ModelThinkingConfigMaxEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for OpenAIErrorResponseErrorType.
const (
	OpenAIErrorResponseErrorTypeApiError            OpenAIErrorResponseErrorType = "api_error"
	OpenAIErrorResponseErrorTypeAuthenticationError OpenAIErrorResponseErrorType = "authentication_error"
	OpenAIErrorResponseErrorTypeInvalidRequestError OpenAIErrorResponseErrorType = "invalid_request_error"
	OpenAIErrorResponseErrorTypePermissionError     OpenAIErrorResponseErrorType = "permission_error"
	OpenAIErrorResponseErrorTypeRateLimitError      OpenAIErrorResponseErrorType = "rate_limit_error"
)

// Valid indicates whether the value is a known member of the OpenAIErrorResponseErrorType enum.
func (e OpenAIErrorResponseErrorType) Valid() bool {
	switch e {
	case OpenAIErrorResponseErrorTypeApiError:
		return true
	case OpenAIErrorResponseErrorTypeAuthenticationError:
		return true
	case OpenAIErrorResponseErrorTypeInvalidRequestError:
		return true
	case OpenAIErrorResponseErrorTypePermissionError:
		return true
	case OpenAIErrorResponseErrorTypeRateLimitError:
		return true
	default:
		return false
	}
}

// Defines values for ResponseContentPartType.
const (
	ResponseContentPartTypeInputImage ResponseContentPartType = "input_image"
	ResponseContentPartTypeInputText  ResponseContentPartType = "input_text"
	ResponseContentPartTypeOutputText ResponseContentPartType = "output_text"
)

// Valid indicates whether the value is a known member of the ResponseContentPartType enum.
func (e ResponseContentPartType) Valid() bool {
	switch e {
	case ResponseContentPartTypeInputImage:
		return true
	case ResponseContentPartTypeInputText:
		return true
	case ResponseContentPartTypeOutputText:
		return true
	default:
		return false
	}
}

// Defines values for ResponseInputItemRole.
const (
	ResponseInputItemRoleAssistant ResponseInputItemRole = "assistant"
	ResponseInputItemRoleDeveloper ResponseInputItemRole = "developer"
	ResponseInputItemRoleSystem    ResponseInputItemRole = "system"
	ResponseInputItemRoleUser      ResponseInputItemRole = "user"
)

// Valid indicates whether the value is a known member of the ResponseInputItemRole enum.
func (e ResponseInputItemRole) Valid() bool {
	switch e {
	case ResponseInputItemRoleAssistant:
		return true
	case ResponseInputItemRoleDeveloper:
		return true
	case ResponseInputItemRoleSystem:
		return true
	case ResponseInputItemRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for ResponseInputItemType.
const (
	ResponseInputItemTypeMessage ResponseInputItemType = "message"
)

// Valid indicates whether the value is a known member of the ResponseInputItemType enum.
func (e ResponseInputItemType) Valid() bool {
	switch e {
	case ResponseInputItemTypeMessage:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOutputContentType.
const (
	ResponseOutputContentTypeOutputText ResponseOutputContentType = "output_text"
	ResponseOutputContentTypeRefusal    ResponseOutputContentType = "refusal"
)

// Valid indicates whether the value is a known member of the ResponseOutputContentType enum.
func (e ResponseOutputContentType) Valid() bool {
	switch e {
	case ResponseOutputContentTypeOutputText:
		return true
	case ResponseOutputContentTypeRefusal:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOutputItemRole.
const (
	ResponseOutputItemRoleAssistant ResponseOutputItemRole = "assistant"
)

// Valid indicates whether the value is a known member of the ResponseOutputItemRole enum.
func (e ResponseOutputItemRole) Valid() bool {
	switch e {
	case ResponseOutputItemRoleAssistant:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOutputItemStatus.
const (
	ResponseOutputItemStatusCompleted  ResponseOutputItemStatus = "completed"
	ResponseOutputItemStatusIncomplete ResponseOutputItemStatus = "incomplete"
)

// Valid indicates whether the value is a known member of the ResponseOutputItemStatus enum.
func (e ResponseOutputItemStatus) Valid() bool {
	switch e {
	case ResponseOutputItemStatusCompleted:
		return true
	case ResponseOutputItemStatusIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOutputItemSummaryType.
const (
	SummaryText ResponseOutputItemSummaryType = "summary_text"
)

// Valid indicates whether the value is a known member of the ResponseOutputItemSummaryType enum.
func (e ResponseOutputItemSummaryType) Valid() bool {
	switch e {
	case SummaryText:
		return true
	default:
		return false
	}
}

// Defines values for ResponseOutputItemType.
const (
	ResponseOutputItemTypeFunctionCall ResponseOutputItemType = "function_call"
	ResponseOutputItemTypeMessage      ResponseOutputItemType = "message"
	ResponseOutputItemTypeReasoning    ResponseOutputItemType = "reasoning"
)

// Valid indicates whether the value is a known member of the ResponseOutputItemType enum.
func (e ResponseOutputItemType) Valid() bool {
	switch e {
	case ResponseOutputItemTypeFunctionCall:
		return true
	case ResponseOutputItemTypeMessage:
		return true
	case ResponseOutputItemTypeReasoning:
		return true
	default:
		return false
	}
}

// Defines values for ResponseReasoningConfigEffort.
const (
	ResponseReasoningConfigEffortHigh    ResponseReasoningConfigEffort = "high"
	ResponseReasoningConfigEffortLow     ResponseReasoningConfigEffort = "low"
	ResponseReasoningConfigEffortMax     ResponseReasoningConfigEffort = "max"
	ResponseReasoningConfigEffortMedium  ResponseReasoningConfigEffort = "medium"
	ResponseReasoningConfigEffortMinimal ResponseReasoningConfigEffort = "minimal"
	ResponseReasoningConfigEffortNone    ResponseReasoningConfigEffort = "none"
	ResponseReasoningConfigEffortXhigh   ResponseReasoningConfigEffort = "xhigh"
)

// Valid indicates whether the value is a known member of the ResponseReasoningConfigEffort enum.
func (e ResponseReasoningConfigEffort) Valid() bool {
	switch e {
	case ResponseReasoningConfigEffortHigh:
		return true
	case ResponseReasoningConfigEffortLow:
		return true
	case ResponseReasoningConfigEffortMax:
		return true
	case ResponseReasoningConfigEffortMedium:
		return true
	case ResponseReasoningConfigEffortMinimal:
		return true
	case ResponseReasoningConfigEffortNone:
		return true
	case ResponseReasoningConfigEffortXhigh:
		return true
	default:
		return false
	}
}

// Defines values for ResponseReasoningConfigSummary.
const (
	ResponseReasoningConfigSummaryAuto     ResponseReasoningConfigSummary = "auto"
	ResponseReasoningConfigSummaryDetailed ResponseReasoningConfigSummary = "detailed"
	ResponseReasoningConfigSummaryNone     ResponseReasoningConfigSummary = "none"
)

// Valid indicates whether the value is a known member of the ResponseReasoningConfigSummary enum.
func (e ResponseReasoningConfigSummary) Valid() bool {
	switch e {
	case ResponseReasoningConfigSummaryAuto:
		return true
	case ResponseReasoningConfigSummaryDetailed:
		return true
	case ResponseReasoningConfigSummaryNone:
		return true
	default:
		return false
	}
}

// Defines values for ResponseResponseObject.
const (
	Response ResponseResponseObject = "response"
)

// Valid indicates whether the value is a known member of the ResponseResponseObject enum.
func (e ResponseResponseObject) Valid() bool {
	switch e {
	case Response:
		return true
	default:
		return false
	}
}

// Defines values for ResponseResponseStatus.
const (
	ResponseResponseStatusCancelled  ResponseResponseStatus = "cancelled"
	ResponseResponseStatusCompleted  ResponseResponseStatus = "completed"
	ResponseResponseStatusFailed     ResponseResponseStatus = "failed"
	ResponseResponseStatusInProgress ResponseResponseStatus = "in_progress"
	ResponseResponseStatusIncomplete ResponseResponseStatus = "incomplete"
)

// Valid indicates whether the value is a known member of the ResponseResponseStatus enum.
func (e ResponseResponseStatus) Valid() bool {
	switch e {
	case ResponseResponseStatusCancelled:
		return true
	case ResponseResponseStatusCompleted:
		return true
	case ResponseResponseStatusFailed:
		return true
	case ResponseResponseStatusInProgress:
		return true
	case ResponseResponseStatusIncomplete:
		return true
	default:
		return false
	}
}

// Defines values for ResponseToolType.
const (
	ResponseToolTypeFunction ResponseToolType = "function"
)

// Valid indicates whether the value is a known member of the ResponseToolType enum.
func (e ResponseToolType) Valid() bool {
	switch e {
	case ResponseToolTypeFunction:
		return true
	default:
		return false
	}
}

// Defines values for ThinkingConfigDisplay.
const (
	Omitted    ThinkingConfigDisplay = "omitted"
	Summarized ThinkingConfigDisplay = "summarized"
)

// Valid indicates whether the value is a known member of the ThinkingConfigDisplay enum.
func (e ThinkingConfigDisplay) Valid() bool {
	switch e {
	case Omitted:
		return true
	case Summarized:
		return true
	default:
		return false
	}
}

// Defines values for ThinkingConfigType.
const (
	Disabled ThinkingConfigType = "disabled"
	Enabled  ThinkingConfigType = "enabled"
)

// Valid indicates whether the value is a known member of the ThinkingConfigType enum.
func (e ThinkingConfigType) Valid() bool {
	switch e {
	case Disabled:
		return true
	case Enabled:
		return true
	default:
		return false
	}
}

// AnthropicContentBlock defines model for AnthropicContentBlock.
type AnthropicContentBlock struct {
	CacheControl *struct {
		Type *AnthropicContentBlockCacheControlType `json:"type,omitempty"`
	} `json:"cache_control,omitempty"`
	Content *AnthropicContentBlock_Content `json:"content,omitempty"`
	Id      *string                        `json:"id,omitempty"`

	// Input Tool input object. Arbitrary user-defined JSON is accepted as-is;
	// the field is intentionally left open (no additionalProperties
	// constraint) so any valid JSON object passes through.
	Input *map[string]interface{} `json:"input,omitempty"`
	Name  *string                 `json:"name,omitempty"`

	// Signature Cryptographic signature for thinking block continuity.
	Signature *string `json:"signature,omitempty"`
	Source    *struct {
		// Data Base64-encoded (standard padded) image bytes. Must decode
		// to a non-empty value within the executor's decoded byte
		// bound. URL-safe alphabet and raw (unpadded) encodings are
		// rejected.
		Data *string `json:"data,omitempty"`

		// MediaType MIME type of the base64-encoded image data.
		MediaType *AnthropicContentBlockSourceMediaType `json:"media_type,omitempty"`
		Type      *AnthropicContentBlockSourceType      `json:"type,omitempty"`
	} `json:"source,omitempty"`
	Text *string `json:"text,omitempty"`

	// Thinking Thinking/reasoning content.
	Thinking  *string                   `json:"thinking,omitempty"`
	ToolUseId *string                   `json:"tool_use_id,omitempty"`
	Type      AnthropicContentBlockType `json:"type"`
}

// AnthropicContentBlockCacheControlType defines model for AnthropicContentBlock.CacheControl.Type.
type AnthropicContentBlockCacheControlType string

// AnthropicContentBlockContent0 defines model for AnthropicContentBlock.Content.0.
type AnthropicContentBlockContent0 = string

// AnthropicContentBlockContent1 defines model for AnthropicContentBlock.Content.1.
type AnthropicContentBlockContent1 = []AnthropicContentBlock

// AnthropicContentBlock_Content defines model for AnthropicContentBlock.Content.
type AnthropicContentBlock_Content struct {
	union json.RawMessage
}

// AnthropicContentBlockSourceMediaType MIME type of the base64-encoded image data.
type AnthropicContentBlockSourceMediaType string

// AnthropicContentBlockSourceType defines model for AnthropicContentBlock.Source.Type.
type AnthropicContentBlockSourceType string

// AnthropicContentBlockType defines model for AnthropicContentBlock.Type.
type AnthropicContentBlockType string

// AnthropicErrorResponse defines model for AnthropicErrorResponse.
type AnthropicErrorResponse struct {
	Error struct {
		// Message Human-readable error message.
		Message string `json:"message"`

		// Type Error type category.
		Type AnthropicErrorResponseErrorType `json:"type"`
	} `json:"error"`

	// RequestId Unique request identifier for debugging.
	RequestId *string `json:"request_id,omitempty"`

	// Type Always "error" for error responses.
	Type AnthropicErrorResponseType `json:"type"`
}

// AnthropicErrorResponseErrorType Error type category.
type AnthropicErrorResponseErrorType string

// AnthropicErrorResponseType Always "error" for error responses.
type AnthropicErrorResponseType string

// AnthropicMessage defines model for AnthropicMessage.
type AnthropicMessage struct {
	Content AnthropicMessage_Content `json:"content"`
	Role    AnthropicMessageRole     `json:"role"`
}

// AnthropicMessageContent0 defines model for AnthropicMessage.Content.0.
type AnthropicMessageContent0 = string

// AnthropicMessageContent1 defines model for AnthropicMessage.Content.1.
type AnthropicMessageContent1 = []AnthropicContentBlock

// AnthropicMessage_Content defines model for AnthropicMessage.Content.
type AnthropicMessage_Content struct {
	union json.RawMessage
}

// AnthropicMessageRole defines model for AnthropicMessage.Role.
type AnthropicMessageRole string

// AnthropicResponseContentBlock defines model for AnthropicResponseContentBlock.
type AnthropicResponseContentBlock struct {
	Id        *string                           `json:"id,omitempty"`
	Input     *map[string]interface{}           `json:"input,omitempty"`
	Name      *string                           `json:"name,omitempty"`
	Signature *string                           `json:"signature,omitempty"`
	Text      *string                           `json:"text,omitempty"`
	Thinking  *string                           `json:"thinking,omitempty"`
	Type      AnthropicResponseContentBlockType `json:"type"`
}

// AnthropicResponseContentBlockType defines model for AnthropicResponseContentBlock.Type.
type AnthropicResponseContentBlockType string

// AnthropicSystemBlock defines model for AnthropicSystemBlock.
type AnthropicSystemBlock struct {
	CacheControl *struct {
		Type *AnthropicSystemBlockCacheControlType `json:"type,omitempty"`
	} `json:"cache_control,omitempty"`
	Text string                   `json:"text"`
	Type AnthropicSystemBlockType `json:"type"`
}

// AnthropicSystemBlockCacheControlType defines model for AnthropicSystemBlock.CacheControl.Type.
type AnthropicSystemBlockCacheControlType string

// AnthropicSystemBlockType defines model for AnthropicSystemBlock.Type.
type AnthropicSystemBlockType string

// AnthropicTool defines model for AnthropicTool.
type AnthropicTool struct {
	CacheControl *struct {
		Type *AnthropicToolCacheControlType `json:"type,omitempty"`
	} `json:"cache_control,omitempty"`
	Description *string `json:"description,omitempty"`

	// InputSchema JSON Schema for tool input. Arbitrary user-defined JSON Schema is
	// accepted as-is; the field is intentionally left open (no
	// additionalProperties constraint) so any valid schema shape passes
	// through.
	InputSchema map[string]interface{} `json:"input_schema"`
	Name        string                 `json:"name"`
}

// AnthropicToolCacheControlType defines model for AnthropicTool.CacheControl.Type.
type AnthropicToolCacheControlType string

// AnthropicToolChoice defines model for AnthropicToolChoice.
type AnthropicToolChoice struct {
	DisableParallelToolUse *bool `json:"disable_parallel_tool_use,omitempty"`

	// Name Required when type=tool.
	Name *string                 `json:"name,omitempty"`
	Type AnthropicToolChoiceType `json:"type"`
}

// AnthropicToolChoiceType defines model for AnthropicToolChoice.Type.
type AnthropicToolChoiceType string

// AnthropicUsage defines model for AnthropicUsage.
type AnthropicUsage struct {
	CacheCreationInputTokens *int `json:"cache_creation_input_tokens,omitempty"`
	CacheReadInputTokens     *int `json:"cache_read_input_tokens,omitempty"`
	InputTokens              int  `json:"input_tokens"`
	OutputTokens             int  `json:"output_tokens"`
}

// ChatCompletionChoice defines model for ChatCompletionChoice.
type ChatCompletionChoice struct {
	FinishReason *ChatCompletionChoiceFinishReason `json:"finish_reason"`
	Index        int                               `json:"index"`
	Logprobs     *map[string]interface{}           `json:"logprobs,omitempty"`

	// Message Response-side chat message used by ChatCompletionChoice.message. Left
	// extensible (no additionalProperties:false) so provider extensions
	// validate; request messages use the closed ChatRequestMessage twin.
	Message *ChatMessage `json:"message,omitempty"`
}

// ChatCompletionChoiceFinishReason defines model for ChatCompletionChoice.FinishReason.
type ChatCompletionChoiceFinishReason string

// ChatCompletionResponse defines model for ChatCompletionResponse.
type ChatCompletionResponse struct {
	Choices []ChatCompletionChoice `json:"choices"`
	Created *int                   `json:"created,omitempty"`

	// Id Completion ID.
	//
	// Example: chatcmpl-abc123
	Id string `json:"id"`

	// Model Model used for completion.
	Model  string                       `json:"model"`
	Object ChatCompletionResponseObject `json:"object"`
	Usage  *ChatUsage                   `json:"usage,omitempty"`
}

// ChatCompletionResponseObject defines model for ChatCompletionResponse.Object.
type ChatCompletionResponseObject string

// ChatContentPart Response-side chat content part used inside ChatMessage.content.
// Left extensible (no additionalProperties:false) so provider extensions
// validate; request content parts use the closed ChatRequestContentPart.
type ChatContentPart struct {
	ImageUrl *struct {
		Detail *ChatContentPartImageUrlDetail `json:"detail,omitempty"`

		// Url Image URL. The executor accepts only bounded HTTPS URLs
		// (scheme https, non-empty host, no userinfo) or bounded
		// data: URLs with an image MIME type and ;base64 encoding.
		// HTTP and other schemes are rejected.
		Url *string `json:"url,omitempty"`
	} `json:"image_url,omitempty"`
	Text *string             `json:"text,omitempty"`
	Type ChatContentPartType `json:"type"`
}

// ChatContentPartImageUrlDetail defines model for ChatContentPart.ImageUrl.Detail.
type ChatContentPartImageUrlDetail string

// ChatContentPartType defines model for ChatContentPart.Type.
type ChatContentPartType string

// ChatMessage Response-side chat message used by ChatCompletionChoice.message. Left
// extensible (no additionalProperties:false) so provider extensions
// validate; request messages use the closed ChatRequestMessage twin.
type ChatMessage struct {
	Content ChatMessage_Content `json:"content"`

	// Name Optional participant name.
	Name *string `json:"name,omitempty"`

	// ReasoningContent Reasoning content from thinking models (assistant messages).
	ReasoningContent *string         `json:"reasoning_content,omitempty"`
	Role             ChatMessageRole `json:"role"`

	// ToolCallId Tool call ID (for role=tool messages).
	ToolCallId *string `json:"tool_call_id,omitempty"`

	// ToolCalls Tool calls made by the assistant.
	ToolCalls *[]ChatToolCall `json:"tool_calls,omitempty"`
}

// ChatMessageContent0 defines model for ChatMessage.Content.0.
type ChatMessageContent0 = string

// ChatMessageContent1 defines model for ChatMessage.Content.1.
type ChatMessageContent1 = []ChatContentPart

// ChatMessage_Content defines model for ChatMessage.Content.
type ChatMessage_Content struct {
	union json.RawMessage
}

// ChatMessageRole defines model for ChatMessage.Role.
type ChatMessageRole string

// ChatRequestContentPart Request-side chat content part. Finite request fields, including the
// image_url nested object, are closed (additionalProperties:false); the
// response-side ChatContentPart stays extensible for provider extensions.
type ChatRequestContentPart struct {
	ImageUrl *struct {
		Detail *ChatRequestContentPartImageUrlDetail `json:"detail,omitempty"`

		// Url Image URL. The executor accepts only bounded HTTPS URLs
		// (scheme https, non-empty host, no userinfo) or bounded
		// data: URLs with an image MIME type and ;base64 encoding.
		// HTTP and other schemes are rejected.
		Url *string `json:"url,omitempty"`
	} `json:"image_url,omitempty"`
	Text *string                    `json:"text,omitempty"`
	Type ChatRequestContentPartType `json:"type"`
}

// ChatRequestContentPartImageUrlDetail defines model for ChatRequestContentPart.ImageUrl.Detail.
type ChatRequestContentPartImageUrlDetail string

// ChatRequestContentPartType defines model for ChatRequestContentPart.Type.
type ChatRequestContentPartType string

// ChatRequestMessage Request-side chat message. Finite request fields are closed
// (additionalProperties:false) so only the documented request shape is
// accepted; the response-side ChatMessage stays extensible (no
// additionalProperties:false) so provider extensions still validate.
type ChatRequestMessage struct {
	Content ChatRequestMessage_Content `json:"content"`

	// Name Optional participant name.
	Name *string `json:"name,omitempty"`

	// ReasoningContent Reasoning content from thinking models (assistant messages).
	ReasoningContent *string                `json:"reasoning_content,omitempty"`
	Role             ChatRequestMessageRole `json:"role"`

	// ToolCallId Tool call ID (for role=tool messages).
	ToolCallId *string `json:"tool_call_id,omitempty"`

	// ToolCalls Tool calls made by the assistant.
	ToolCalls *[]ChatRequestToolCall `json:"tool_calls,omitempty"`
}

// ChatRequestMessageContent0 defines model for ChatRequestMessage.Content.0.
type ChatRequestMessageContent0 = string

// ChatRequestMessageContent1 defines model for ChatRequestMessage.Content.1.
type ChatRequestMessageContent1 = []ChatRequestContentPart

// ChatRequestMessage_Content defines model for ChatRequestMessage.Content.
type ChatRequestMessage_Content struct {
	union json.RawMessage
}

// ChatRequestMessageRole defines model for ChatRequestMessage.Role.
type ChatRequestMessageRole string

// ChatRequestToolCall Request-side chat tool call. Finite request fields, including the
// function nested object, are closed (additionalProperties:false); the
// response-side ChatToolCall stays extensible for provider extensions.
type ChatRequestToolCall struct {
	Function struct {
		Arguments string `json:"arguments"`
		Name      string `json:"name"`
	} `json:"function"`
	Id   string                  `json:"id"`
	Type ChatRequestToolCallType `json:"type"`
}

// ChatRequestToolCallType defines model for ChatRequestToolCall.Type.
type ChatRequestToolCallType string

// ChatTool defines model for ChatTool.
type ChatTool struct {
	Function struct {
		Description *string `json:"description,omitempty"`
		Name        string  `json:"name"`

		// Parameters JSON Schema for function parameters. Arbitrary user-defined
		// JSON Schema is accepted as-is; the field is intentionally left
		// open (no additionalProperties constraint) so any valid schema
		// shape passes through.
		Parameters map[string]interface{} `json:"parameters"`
		Strict     *bool                  `json:"strict,omitempty"`
	} `json:"function"`
	Type ChatToolType `json:"type"`
}

// ChatToolType defines model for ChatTool.Type.
type ChatToolType string

// ChatToolCall Response-side chat tool call used inside ChatMessage.tool_calls. Left
// extensible (no additionalProperties:false) so provider extensions
// validate; request tool calls use the closed ChatRequestToolCall twin.
type ChatToolCall struct {
	Function struct {
		Arguments string `json:"arguments"`
		Name      string `json:"name"`
	} `json:"function"`
	Id   string           `json:"id"`
	Type ChatToolCallType `json:"type"`
}

// ChatToolCallType defines model for ChatToolCall.Type.
type ChatToolCallType string

// ChatToolChoice defines model for ChatToolChoice.
type ChatToolChoice struct {
	Function struct {
		Name string `json:"name"`
	} `json:"function"`
	Type ChatToolChoiceType `json:"type"`
}

// ChatToolChoiceType defines model for ChatToolChoice.Type.
type ChatToolChoiceType string

// ChatUsage defines model for ChatUsage.
type ChatUsage struct {
	CompletionTokens        int `json:"completion_tokens"`
	CompletionTokensDetails *struct {
		AcceptedPredictionTokens *int `json:"accepted_prediction_tokens,omitempty"`

		// ReasoningTokens Tokens used for reasoning/thinking.
		ReasoningTokens          *int `json:"reasoning_tokens,omitempty"`
		RejectedPredictionTokens *int `json:"rejected_prediction_tokens,omitempty"`
	} `json:"completion_tokens_details,omitempty"`
	PromptTokens        int `json:"prompt_tokens"`
	PromptTokensDetails *struct {
		CachedTokens *int `json:"cached_tokens,omitempty"`
	} `json:"prompt_tokens_details,omitempty"`
	TotalTokens int `json:"total_tokens"`
}

// CreateChatCompletionRequest defines model for CreateChatCompletionRequest.
type CreateChatCompletionRequest struct {
	// MaxCompletionTokens Maximum total output tokens including reasoning tokens.
	MaxCompletionTokens *int `json:"max_completion_tokens,omitempty"`

	// MaxTokens Maximum output tokens (does not include reasoning tokens).
	MaxTokens *int                 `json:"max_tokens,omitempty"`
	Messages  []ChatRequestMessage `json:"messages"`

	// Model Model selector. Supports extended syntax:
	// - `gpt-4o` — base model
	// - `gpt-4o:fast` — with route group
	// - `gpt-4o@openai` — with provider
	// - `gpt-4o:fast@openai` — with route group and provider
	// - `auto` — automatic selection
	//
	//
	// Example: gpt-4o
	Model string `json:"model"`

	// ReasoningEffort Thinking/reasoning depth. Only effective for models with `thinking` capability.
	// Maps to upstream-native parameters automatically.
	ReasoningEffort *CreateChatCompletionRequestReasoningEffort `json:"reasoning_effort,omitempty"`

	// ResponseFormat Output format constraint.
	ResponseFormat *struct {
		Type *CreateChatCompletionRequestResponseFormatType `json:"type,omitempty"`
	} `json:"response_format,omitempty"`

	// Stop Stop sequences.
	Stop *CreateChatCompletionRequest_Stop `json:"stop,omitempty"`

	// Stream Whether to stream the response as SSE.
	Stream *bool `json:"stream,omitempty"`

	// Temperature Sampling temperature.
	Temperature *float32 `json:"temperature,omitempty"`

	// ToolChoice Tool selection strategy.
	ToolChoice *CreateChatCompletionRequest_ToolChoice `json:"tool_choice,omitempty"`

	// Tools Function calling tools.
	Tools *[]ChatTool `json:"tools,omitempty"`

	// TopP Nucleus sampling probability.
	TopP *float32 `json:"top_p,omitempty"`

	// User End-user identifier for abuse monitoring.
	User *string `json:"user,omitempty"`
}

// CreateChatCompletionRequestReasoningEffort Thinking/reasoning depth. Only effective for models with `thinking` capability.
// Maps to upstream-native parameters automatically.
type CreateChatCompletionRequestReasoningEffort string

// CreateChatCompletionRequestResponseFormatType defines model for CreateChatCompletionRequest.ResponseFormat.Type.
type CreateChatCompletionRequestResponseFormatType string

// CreateChatCompletionRequestStop0 defines model for CreateChatCompletionRequest.Stop.0.
type CreateChatCompletionRequestStop0 = string

// CreateChatCompletionRequestStop1 defines model for CreateChatCompletionRequest.Stop.1.
type CreateChatCompletionRequestStop1 = []string

// CreateChatCompletionRequest_Stop Stop sequences.
type CreateChatCompletionRequest_Stop struct {
	union json.RawMessage
}

// CreateChatCompletionRequestToolChoice0 defines model for CreateChatCompletionRequest.ToolChoice.0.
type CreateChatCompletionRequestToolChoice0 string

// CreateChatCompletionRequest_ToolChoice Tool selection strategy.
type CreateChatCompletionRequest_ToolChoice struct {
	union json.RawMessage
}

// CreateImageRequest defines model for CreateImageRequest.
type CreateImageRequest struct {
	// Model Image model selector.
	//
	// Example: dall-e-3
	Model string `json:"model"`

	// N Number of images to generate.
	N *int `json:"n,omitempty"`

	// Prompt Image description.
	Prompt         string                            `json:"prompt"`
	Quality        *CreateImageRequestQuality        `json:"quality,omitempty"`
	ResponseFormat *CreateImageRequestResponseFormat `json:"response_format,omitempty"`
	Size           *CreateImageRequestSize           `json:"size,omitempty"`
	Style          *CreateImageRequestStyle          `json:"style,omitempty"`
	User           *string                           `json:"user,omitempty"`
}

// CreateImageRequestQuality defines model for CreateImageRequest.Quality.
type CreateImageRequestQuality string

// CreateImageRequestResponseFormat defines model for CreateImageRequest.ResponseFormat.
type CreateImageRequestResponseFormat string

// CreateImageRequestSize defines model for CreateImageRequest.Size.
type CreateImageRequestSize string

// CreateImageRequestStyle defines model for CreateImageRequest.Style.
type CreateImageRequestStyle string

// CreateImageResponse defines model for CreateImageResponse.
type CreateImageResponse struct {
	Created int `json:"created"`
	Data    []struct {
		B64Json       *string `json:"b64_json,omitempty"`
		RevisedPrompt *string `json:"revised_prompt,omitempty"`
		Url           *string `json:"url,omitempty"`
	} `json:"data"`
}

// CreateMessageRequest defines model for CreateMessageRequest.
type CreateMessageRequest struct {
	// MaxTokens Maximum output tokens.
	MaxTokens int                `json:"max_tokens"`
	Messages  []AnthropicMessage `json:"messages"`
	Metadata  *struct {
		UserId *string `json:"user_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Model Model selector (extended syntax supported).
	//
	// Example: claude-3-opus-20240229
	Model         string    `json:"model"`
	StopSequences *[]string `json:"stop_sequences,omitempty"`
	Stream        *bool     `json:"stream,omitempty"`

	// System System prompt.
	System      *CreateMessageRequest_System `json:"system,omitempty"`
	Temperature *float32                     `json:"temperature,omitempty"`
	Thinking    *ThinkingConfig              `json:"thinking,omitempty"`
	ToolChoice  *AnthropicToolChoice         `json:"tool_choice,omitempty"`
	Tools       *[]AnthropicTool             `json:"tools,omitempty"`
	TopK        *int                         `json:"top_k,omitempty"`
	TopP        *float32                     `json:"top_p,omitempty"`
}

// CreateMessageRequestSystem0 defines model for CreateMessageRequest.System.0.
type CreateMessageRequestSystem0 = string

// CreateMessageRequestSystem1 defines model for CreateMessageRequest.System.1.
type CreateMessageRequestSystem1 = []AnthropicSystemBlock

// CreateMessageRequest_System System prompt.
type CreateMessageRequest_System struct {
	union json.RawMessage
}

// CreateMessageResponse defines model for CreateMessageResponse.
type CreateMessageResponse struct {
	Content []AnthropicResponseContentBlock `json:"content"`

	// Id Example: msg_abc123
	Id           string                           `json:"id"`
	Model        string                           `json:"model"`
	Role         CreateMessageResponseRole        `json:"role"`
	StopReason   *CreateMessageResponseStopReason `json:"stop_reason"`
	StopSequence *string                          `json:"stop_sequence,omitempty"`
	Type         CreateMessageResponseType        `json:"type"`
	Usage        AnthropicUsage                   `json:"usage"`
}

// CreateMessageResponseRole defines model for CreateMessageResponse.Role.
type CreateMessageResponseRole string

// CreateMessageResponseStopReason defines model for CreateMessageResponse.StopReason.
type CreateMessageResponseStopReason string

// CreateMessageResponseType defines model for CreateMessageResponse.Type.
type CreateMessageResponseType string

// CreateResponseRequest defines model for CreateResponseRequest.
type CreateResponseRequest struct {
	// Input Input text or message array.
	Input CreateResponseRequest_Input `json:"input"`

	// Instructions System instructions.
	Instructions    *string `json:"instructions,omitempty"`
	MaxOutputTokens *int    `json:"max_output_tokens,omitempty"`
	Metadata        *struct {
		UserId *string `json:"user_id,omitempty"`
	} `json:"metadata,omitempty"`

	// Model Model selector (extended syntax supported).
	//
	// Example: gpt-4o
	Model       string                   `json:"model"`
	Reasoning   *ResponseReasoningConfig `json:"reasoning,omitempty"`
	Stream      *bool                    `json:"stream,omitempty"`
	Temperature *float32                 `json:"temperature,omitempty"`
	Text        *struct {
		Format *struct {
			Name *string `json:"name,omitempty"`

			// Schema JSON Schema for structured output. Arbitrary user-defined
			// JSON Schema is accepted as-is; the field is intentionally
			// left open (no additionalProperties constraint).
			Schema *map[string]interface{}              `json:"schema,omitempty"`
			Type   *CreateResponseRequestTextFormatType `json:"type,omitempty"`
		} `json:"format,omitempty"`
	} `json:"text,omitempty"`
	ToolChoice *CreateResponseRequestToolChoice `json:"tool_choice,omitempty"`
	Tools      *[]ResponseTool                  `json:"tools,omitempty"`
	TopP       *float32                         `json:"top_p,omitempty"`
}

// CreateResponseRequestInput0 defines model for CreateResponseRequest.Input.0.
type CreateResponseRequestInput0 = string

// CreateResponseRequestInput1 defines model for CreateResponseRequest.Input.1.
type CreateResponseRequestInput1 = []ResponseInputItem

// CreateResponseRequest_Input Input text or message array.
type CreateResponseRequest_Input struct {
	union json.RawMessage
}

// CreateResponseRequestTextFormatType defines model for CreateResponseRequest.Text.Format.Type.
type CreateResponseRequestTextFormatType string

// CreateResponseRequestToolChoice defines model for CreateResponseRequest.ToolChoice.
type CreateResponseRequestToolChoice string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Example: ok
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus Example: ok
type HealthResponseStatus string

// ModelListResponse defines model for ModelListResponse.
type ModelListResponse struct {
	Data   []ModelObject           `json:"data"`
	Object ModelListResponseObject `json:"object"`
}

// ModelListResponseObject defines model for ModelListResponse.Object.
type ModelListResponseObject string

// ModelObject defines model for ModelObject.
type ModelObject struct {
	// Capabilities Model capability tags.
	//
	// Example: ["text","vision","function_calling"]
	Capabilities *[]ModelObjectCapabilities `json:"capabilities,omitempty"`

	// ContextWindow Context window token count.
	//
	// Example: 128000
	ContextWindow *int `json:"context_window,omitempty"`

	// Created Unix timestamp when the model was registered.
	Created *int `json:"created,omitempty"`

	// Id Model identifier (supports selector syntax for routing).
	//
	// Example: gpt-4o
	Id string `json:"id"`

	// MaxOutputTokens Maximum output token count.
	//
	// Example: 16384
	MaxOutputTokens *int              `json:"max_output_tokens,omitempty"`
	Object          ModelObjectObject `json:"object"`

	// OwnedBy Source identifier.
	//
	// Example: tokenmp
	OwnedBy  string               `json:"owned_by"`
	Thinking *ModelThinkingConfig `json:"thinking,omitempty"`
}

// ModelObjectCapabilities defines model for ModelObject.Capabilities.
type ModelObjectCapabilities string

// ModelObjectObject defines model for ModelObject.Object.
type ModelObjectObject string

// ModelThinkingConfig defines model for ModelThinkingConfig.
type ModelThinkingConfig struct {
	// DefaultEffort Default effort when user does not specify.
	//
	// Example: medium
	DefaultEffort ModelThinkingConfigDefaultEffort `json:"default_effort"`

	// EffortLevels All effort levels supported by this model.
	//
	// Example: ["none","minimal","low","medium","high","xhigh","max"]
	EffortLevels []ModelThinkingConfigEffortLevels `json:"effort_levels"`

	// MaxBudgetTokens Maximum thinking budget tokens (Anthropic-style models).
	//
	// Example: 64000
	MaxBudgetTokens *int `json:"max_budget_tokens,omitempty"`

	// MaxEffort Maximum effort supported by this model.
	//
	// Example: max
	MaxEffort ModelThinkingConfigMaxEffort `json:"max_effort"`

	// MinBudgetTokens Minimum thinking budget tokens (Anthropic-style models).
	//
	// Example: 1024
	MinBudgetTokens *int `json:"min_budget_tokens,omitempty"`

	// Supported Whether the model supports thinking/reasoning.
	//
	// Example: true
	Supported bool `json:"supported"`
}

// ModelThinkingConfigDefaultEffort Default effort when user does not specify.
//
// Example: medium
type ModelThinkingConfigDefaultEffort string

// ModelThinkingConfigEffortLevels defines model for ModelThinkingConfig.EffortLevels.
type ModelThinkingConfigEffortLevels string

// ModelThinkingConfigMaxEffort Maximum effort supported by this model.
//
// Example: max
type ModelThinkingConfigMaxEffort string

// OpenAIErrorResponse defines model for OpenAIErrorResponse.
type OpenAIErrorResponse struct {
	Error struct {
		// Code Stable error code for programmatic handling.
		Code *string `json:"code,omitempty"`

		// Message Human-readable error message.
		Message string `json:"message"`

		// Param The parameter that caused the error.
		Param *string `json:"param,omitempty"`

		// Type Error type category.
		Type OpenAIErrorResponseErrorType `json:"type"`
	} `json:"error"`

	// Status HTTP status code (mirrors response status).
	Status *int `json:"status,omitempty"`
}

// OpenAIErrorResponseErrorType Error type category.
type OpenAIErrorResponseErrorType string

// ResponseContentPart defines model for ResponseContentPart.
type ResponseContentPart struct {
	// ImageUrl Image URL. The executor accepts only bounded HTTPS URLs
	// (scheme https, non-empty host, no userinfo) or bounded
	// data: URLs with an image MIME type and ;base64 encoding.
	// HTTP and other schemes are rejected.
	ImageUrl *string                 `json:"image_url,omitempty"`
	Text     *string                 `json:"text,omitempty"`
	Type     ResponseContentPartType `json:"type"`
}

// ResponseContentPartType defines model for ResponseContentPart.Type.
type ResponseContentPartType string

// ResponseInputItem defines model for ResponseInputItem.
type ResponseInputItem struct {
	Content *ResponseInputItem_Content `json:"content,omitempty"`
	Role    *ResponseInputItemRole     `json:"role,omitempty"`
	Type    ResponseInputItemType      `json:"type"`
}

// ResponseInputItemContent0 defines model for ResponseInputItem.Content.0.
type ResponseInputItemContent0 = string

// ResponseInputItemContent1 defines model for ResponseInputItem.Content.1.
type ResponseInputItemContent1 = []ResponseContentPart

// ResponseInputItem_Content defines model for ResponseInputItem.Content.
type ResponseInputItem_Content struct {
	union json.RawMessage
}

// ResponseInputItemRole defines model for ResponseInputItem.Role.
type ResponseInputItemRole string

// ResponseInputItemType defines model for ResponseInputItem.Type.
type ResponseInputItemType string

// ResponseOutputContent defines model for ResponseOutputContent.
type ResponseOutputContent struct {
	Annotations *[]map[string]interface{} `json:"annotations,omitempty"`
	Text        *string                   `json:"text,omitempty"`
	Type        ResponseOutputContentType `json:"type"`
}

// ResponseOutputContentType defines model for ResponseOutputContent.Type.
type ResponseOutputContentType string

// ResponseOutputItem defines model for ResponseOutputItem.
type ResponseOutputItem struct {
	Arguments *string                   `json:"arguments,omitempty"`
	CallId    *string                   `json:"call_id,omitempty"`
	Content   *[]ResponseOutputContent  `json:"content,omitempty"`
	Id        *string                   `json:"id,omitempty"`
	Name      *string                   `json:"name,omitempty"`
	Role      *ResponseOutputItemRole   `json:"role,omitempty"`
	Status    *ResponseOutputItemStatus `json:"status,omitempty"`
	Summary   *[]struct {
		Text *string                        `json:"text,omitempty"`
		Type *ResponseOutputItemSummaryType `json:"type,omitempty"`
	} `json:"summary,omitempty"`
	Type ResponseOutputItemType `json:"type"`
}

// ResponseOutputItemRole defines model for ResponseOutputItem.Role.
type ResponseOutputItemRole string

// ResponseOutputItemStatus defines model for ResponseOutputItem.Status.
type ResponseOutputItemStatus string

// ResponseOutputItemSummaryType defines model for ResponseOutputItem.Summary.Type.
type ResponseOutputItemSummaryType string

// ResponseOutputItemType defines model for ResponseOutputItem.Type.
type ResponseOutputItemType string

// ResponseReasoningConfig defines model for ResponseReasoningConfig.
type ResponseReasoningConfig struct {
	// Effort Reasoning effort level. Only effective for models with `thinking` capability.
	Effort *ResponseReasoningConfigEffort `json:"effort,omitempty"`

	// Summary Controls reasoning summary in response.
	Summary *ResponseReasoningConfigSummary `json:"summary,omitempty"`
}

// ResponseReasoningConfigEffort Reasoning effort level. Only effective for models with `thinking` capability.
type ResponseReasoningConfigEffort string

// ResponseReasoningConfigSummary Controls reasoning summary in response.
type ResponseReasoningConfigSummary string

// ResponseResponse defines model for ResponseResponse.
type ResponseResponse struct {
	CreatedAt *int `json:"created_at,omitempty"`
	Error     *struct {
		Code    *string `json:"code,omitempty"`
		Message *string `json:"message,omitempty"`
		Type    *string `json:"type,omitempty"`
	} `json:"error,omitempty"`

	// Id Example: resp_abc123
	Id                string `json:"id"`
	IncompleteDetails *struct {
		Reason *string `json:"reason,omitempty"`
	} `json:"incomplete_details,omitempty"`
	Model  *string                `json:"model,omitempty"`
	Object ResponseResponseObject `json:"object"`
	Output []ResponseOutputItem   `json:"output"`
	Status ResponseResponseStatus `json:"status"`
	Usage  ResponseUsage          `json:"usage"`
}

// ResponseResponseObject defines model for ResponseResponse.Object.
type ResponseResponseObject string

// ResponseResponseStatus defines model for ResponseResponse.Status.
type ResponseResponseStatus string

// ResponseTool defines model for ResponseTool.
type ResponseTool struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`

	// Parameters JSON Schema for function parameters. Arbitrary user-defined JSON
	// Schema is accepted as-is; the field is intentionally left open
	// (no additionalProperties constraint).
	Parameters map[string]interface{} `json:"parameters"`
	Strict     *bool                  `json:"strict,omitempty"`
	Type       ResponseToolType       `json:"type"`
}

// ResponseToolType defines model for ResponseTool.Type.
type ResponseToolType string

// ResponseUsage defines model for ResponseUsage.
type ResponseUsage struct {
	InputTokens        int `json:"input_tokens"`
	InputTokensDetails *struct {
		CachedTokens *int `json:"cached_tokens,omitempty"`
	} `json:"input_tokens_details,omitempty"`
	OutputTokens        int `json:"output_tokens"`
	OutputTokensDetails *struct {
		ReasoningTokens *int `json:"reasoning_tokens,omitempty"`
	} `json:"output_tokens_details,omitempty"`
	TotalTokens int `json:"total_tokens"`
}

// ThinkingConfig defines model for ThinkingConfig.
type ThinkingConfig struct {
	// BudgetTokens Thinking token budget. Required when type=enabled and must be
	// >= 1024 and strictly less than max_tokens (budget_tokens <
	// max_tokens). When type=disabled this field must be omitted.
	// Only valid when type=enabled.
	BudgetTokens *int `json:"budget_tokens,omitempty"`

	// Display Controls thinking content in response.
	// "summarized" returns thinking text, "omitted" returns only signature.
	Display *ThinkingConfigDisplay `json:"display,omitempty"`

	// Type Whether thinking is enabled.
	Type ThinkingConfigType `json:"type"`
}

// ThinkingConfigDisplay Controls thinking content in response.
// "summarized" returns thinking text, "omitted" returns only signature.
type ThinkingConfigDisplay string

// ThinkingConfigType Whether thinking is enabled.
type ThinkingConfigType string

// AnthropicBadRequest defines model for AnthropicBadRequest.
type AnthropicBadRequest = AnthropicErrorResponse

// AnthropicNotFound defines model for AnthropicNotFound.
type AnthropicNotFound = AnthropicErrorResponse

// AnthropicNotImplemented defines model for AnthropicNotImplemented.
type AnthropicNotImplemented = AnthropicErrorResponse

// AnthropicOverloaded defines model for AnthropicOverloaded.
type AnthropicOverloaded = AnthropicErrorResponse

// AnthropicPermissionDenied defines model for AnthropicPermissionDenied.
type AnthropicPermissionDenied = AnthropicErrorResponse

// AnthropicRateLimit defines model for AnthropicRateLimit.
type AnthropicRateLimit = AnthropicErrorResponse

// AnthropicServerError defines model for AnthropicServerError.
type AnthropicServerError = AnthropicErrorResponse

// AnthropicUnauthorized defines model for AnthropicUnauthorized.
type AnthropicUnauthorized = AnthropicErrorResponse

// OpenAIBadRequest defines model for OpenAIBadRequest.
type OpenAIBadRequest = OpenAIErrorResponse

// OpenAINotFound defines model for OpenAINotFound.
type OpenAINotFound = OpenAIErrorResponse

// OpenAINotImplemented defines model for OpenAINotImplemented.
type OpenAINotImplemented = OpenAIErrorResponse

// OpenAIPermissionDenied defines model for OpenAIPermissionDenied.
type OpenAIPermissionDenied = OpenAIErrorResponse

// OpenAIRateLimit defines model for OpenAIRateLimit.
type OpenAIRateLimit = OpenAIErrorResponse

// OpenAIServerError defines model for OpenAIServerError.
type OpenAIServerError = OpenAIErrorResponse

// OpenAIUnauthorized defines model for OpenAIUnauthorized.
type OpenAIUnauthorized = OpenAIErrorResponse

// OpenAIUpstreamError defines model for OpenAIUpstreamError.
type OpenAIUpstreamError = OpenAIErrorResponse

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = CreateChatCompletionRequest

// CreateImageJSONRequestBody defines body for CreateImage for application/json ContentType.
type CreateImageJSONRequestBody = CreateImageRequest

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody = CreateMessageRequest

// CreateResponseJSONRequestBody defines body for CreateResponse for application/json ContentType.
type CreateResponseJSONRequestBody = CreateResponseRequest

// AsAnthropicContentBlockContent0 returns the union data inside the AnthropicContentBlock_Content as a AnthropicContentBlockContent0
func (t AnthropicContentBlock_Content) AsAnthropicContentBlockContent0() (AnthropicContentBlockContent0, error) {
	var body AnthropicContentBlockContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnthropicContentBlockContent0 overwrites any union data inside the AnthropicContentBlock_Content as the provided AnthropicContentBlockContent0
func (t *AnthropicContentBlock_Content) FromAnthropicContentBlockContent0(v AnthropicContentBlockContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnthropicContentBlockContent0 performs a merge with any union data inside the AnthropicContentBlock_Content, using the provided AnthropicContentBlockContent0
func (t *AnthropicContentBlock_Content) MergeAnthropicContentBlockContent0(v AnthropicContentBlockContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnthropicContentBlockContent1 returns the union data inside the AnthropicContentBlock_Content as a AnthropicContentBlockContent1
func (t AnthropicContentBlock_Content) AsAnthropicContentBlockContent1() (AnthropicContentBlockContent1, error) {
	var body AnthropicContentBlockContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnthropicContentBlockContent1 overwrites any union data inside the AnthropicContentBlock_Content as the provided AnthropicContentBlockContent1
func (t *AnthropicContentBlock_Content) FromAnthropicContentBlockContent1(v AnthropicContentBlockContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnthropicContentBlockContent1 performs a merge with any union data inside the AnthropicContentBlock_Content, using the provided AnthropicContentBlockContent1
func (t *AnthropicContentBlock_Content) MergeAnthropicContentBlockContent1(v AnthropicContentBlockContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnthropicContentBlock_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnthropicContentBlock_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsAnthropicMessageContent0 returns the union data inside the AnthropicMessage_Content as a AnthropicMessageContent0
func (t AnthropicMessage_Content) AsAnthropicMessageContent0() (AnthropicMessageContent0, error) {
	var body AnthropicMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnthropicMessageContent0 overwrites any union data inside the AnthropicMessage_Content as the provided AnthropicMessageContent0
func (t *AnthropicMessage_Content) FromAnthropicMessageContent0(v AnthropicMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnthropicMessageContent0 performs a merge with any union data inside the AnthropicMessage_Content, using the provided AnthropicMessageContent0
func (t *AnthropicMessage_Content) MergeAnthropicMessageContent0(v AnthropicMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAnthropicMessageContent1 returns the union data inside the AnthropicMessage_Content as a AnthropicMessageContent1
func (t AnthropicMessage_Content) AsAnthropicMessageContent1() (AnthropicMessageContent1, error) {
	var body AnthropicMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAnthropicMessageContent1 overwrites any union data inside the AnthropicMessage_Content as the provided AnthropicMessageContent1
func (t *AnthropicMessage_Content) FromAnthropicMessageContent1(v AnthropicMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAnthropicMessageContent1 performs a merge with any union data inside the AnthropicMessage_Content, using the provided AnthropicMessageContent1
func (t *AnthropicMessage_Content) MergeAnthropicMessageContent1(v AnthropicMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AnthropicMessage_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *AnthropicMessage_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChatMessageContent0 returns the union data inside the ChatMessage_Content as a ChatMessageContent0
func (t ChatMessage_Content) AsChatMessageContent0() (ChatMessageContent0, error) {
	var body ChatMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent0 overwrites any union data inside the ChatMessage_Content as the provided ChatMessageContent0
func (t *ChatMessage_Content) FromChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent0 performs a merge with any union data inside the ChatMessage_Content, using the provided ChatMessageContent0
func (t *ChatMessage_Content) MergeChatMessageContent0(v ChatMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatMessageContent1 returns the union data inside the ChatMessage_Content as a ChatMessageContent1
func (t ChatMessage_Content) AsChatMessageContent1() (ChatMessageContent1, error) {
	var body ChatMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatMessageContent1 overwrites any union data inside the ChatMessage_Content as the provided ChatMessageContent1
func (t *ChatMessage_Content) FromChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatMessageContent1 performs a merge with any union data inside the ChatMessage_Content, using the provided ChatMessageContent1
func (t *ChatMessage_Content) MergeChatMessageContent1(v ChatMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatMessage_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatMessage_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsChatRequestMessageContent0 returns the union data inside the ChatRequestMessage_Content as a ChatRequestMessageContent0
func (t ChatRequestMessage_Content) AsChatRequestMessageContent0() (ChatRequestMessageContent0, error) {
	var body ChatRequestMessageContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatRequestMessageContent0 overwrites any union data inside the ChatRequestMessage_Content as the provided ChatRequestMessageContent0
func (t *ChatRequestMessage_Content) FromChatRequestMessageContent0(v ChatRequestMessageContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatRequestMessageContent0 performs a merge with any union data inside the ChatRequestMessage_Content, using the provided ChatRequestMessageContent0
func (t *ChatRequestMessage_Content) MergeChatRequestMessageContent0(v ChatRequestMessageContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatRequestMessageContent1 returns the union data inside the ChatRequestMessage_Content as a ChatRequestMessageContent1
func (t ChatRequestMessage_Content) AsChatRequestMessageContent1() (ChatRequestMessageContent1, error) {
	var body ChatRequestMessageContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatRequestMessageContent1 overwrites any union data inside the ChatRequestMessage_Content as the provided ChatRequestMessageContent1
func (t *ChatRequestMessage_Content) FromChatRequestMessageContent1(v ChatRequestMessageContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatRequestMessageContent1 performs a merge with any union data inside the ChatRequestMessage_Content, using the provided ChatRequestMessageContent1
func (t *ChatRequestMessage_Content) MergeChatRequestMessageContent1(v ChatRequestMessageContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatRequestMessage_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatRequestMessage_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateChatCompletionRequestStop0 returns the union data inside the CreateChatCompletionRequest_Stop as a CreateChatCompletionRequestStop0
func (t CreateChatCompletionRequest_Stop) AsCreateChatCompletionRequestStop0() (CreateChatCompletionRequestStop0, error) {
	var body CreateChatCompletionRequestStop0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChatCompletionRequestStop0 overwrites any union data inside the CreateChatCompletionRequest_Stop as the provided CreateChatCompletionRequestStop0
func (t *CreateChatCompletionRequest_Stop) FromCreateChatCompletionRequestStop0(v CreateChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChatCompletionRequestStop0 performs a merge with any union data inside the CreateChatCompletionRequest_Stop, using the provided CreateChatCompletionRequestStop0
func (t *CreateChatCompletionRequest_Stop) MergeCreateChatCompletionRequestStop0(v CreateChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateChatCompletionRequestStop1 returns the union data inside the CreateChatCompletionRequest_Stop as a CreateChatCompletionRequestStop1
func (t CreateChatCompletionRequest_Stop) AsCreateChatCompletionRequestStop1() (CreateChatCompletionRequestStop1, error) {
	var body CreateChatCompletionRequestStop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChatCompletionRequestStop1 overwrites any union data inside the CreateChatCompletionRequest_Stop as the provided CreateChatCompletionRequestStop1
func (t *CreateChatCompletionRequest_Stop) FromCreateChatCompletionRequestStop1(v CreateChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChatCompletionRequestStop1 performs a merge with any union data inside the CreateChatCompletionRequest_Stop, using the provided CreateChatCompletionRequestStop1
func (t *CreateChatCompletionRequest_Stop) MergeCreateChatCompletionRequestStop1(v CreateChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateChatCompletionRequest_Stop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateChatCompletionRequest_Stop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateChatCompletionRequestToolChoice0 returns the union data inside the CreateChatCompletionRequest_ToolChoice as a CreateChatCompletionRequestToolChoice0
func (t CreateChatCompletionRequest_ToolChoice) AsCreateChatCompletionRequestToolChoice0() (CreateChatCompletionRequestToolChoice0, error) {
	var body CreateChatCompletionRequestToolChoice0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateChatCompletionRequestToolChoice0 overwrites any union data inside the CreateChatCompletionRequest_ToolChoice as the provided CreateChatCompletionRequestToolChoice0
func (t *CreateChatCompletionRequest_ToolChoice) FromCreateChatCompletionRequestToolChoice0(v CreateChatCompletionRequestToolChoice0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateChatCompletionRequestToolChoice0 performs a merge with any union data inside the CreateChatCompletionRequest_ToolChoice, using the provided CreateChatCompletionRequestToolChoice0
func (t *CreateChatCompletionRequest_ToolChoice) MergeCreateChatCompletionRequestToolChoice0(v CreateChatCompletionRequestToolChoice0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatToolChoice returns the union data inside the CreateChatCompletionRequest_ToolChoice as a ChatToolChoice
func (t CreateChatCompletionRequest_ToolChoice) AsChatToolChoice() (ChatToolChoice, error) {
	var body ChatToolChoice
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatToolChoice overwrites any union data inside the CreateChatCompletionRequest_ToolChoice as the provided ChatToolChoice
func (t *CreateChatCompletionRequest_ToolChoice) FromChatToolChoice(v ChatToolChoice) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatToolChoice performs a merge with any union data inside the CreateChatCompletionRequest_ToolChoice, using the provided ChatToolChoice
func (t *CreateChatCompletionRequest_ToolChoice) MergeChatToolChoice(v ChatToolChoice) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateChatCompletionRequest_ToolChoice) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateChatCompletionRequest_ToolChoice) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateMessageRequestSystem0 returns the union data inside the CreateMessageRequest_System as a CreateMessageRequestSystem0
func (t CreateMessageRequest_System) AsCreateMessageRequestSystem0() (CreateMessageRequestSystem0, error) {
	var body CreateMessageRequestSystem0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateMessageRequestSystem0 overwrites any union data inside the CreateMessageRequest_System as the provided CreateMessageRequestSystem0
func (t *CreateMessageRequest_System) FromCreateMessageRequestSystem0(v CreateMessageRequestSystem0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateMessageRequestSystem0 performs a merge with any union data inside the CreateMessageRequest_System, using the provided CreateMessageRequestSystem0
func (t *CreateMessageRequest_System) MergeCreateMessageRequestSystem0(v CreateMessageRequestSystem0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateMessageRequestSystem1 returns the union data inside the CreateMessageRequest_System as a CreateMessageRequestSystem1
func (t CreateMessageRequest_System) AsCreateMessageRequestSystem1() (CreateMessageRequestSystem1, error) {
	var body CreateMessageRequestSystem1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateMessageRequestSystem1 overwrites any union data inside the CreateMessageRequest_System as the provided CreateMessageRequestSystem1
func (t *CreateMessageRequest_System) FromCreateMessageRequestSystem1(v CreateMessageRequestSystem1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateMessageRequestSystem1 performs a merge with any union data inside the CreateMessageRequest_System, using the provided CreateMessageRequestSystem1
func (t *CreateMessageRequest_System) MergeCreateMessageRequestSystem1(v CreateMessageRequestSystem1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateMessageRequest_System) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateMessageRequest_System) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsCreateResponseRequestInput0 returns the union data inside the CreateResponseRequest_Input as a CreateResponseRequestInput0
func (t CreateResponseRequest_Input) AsCreateResponseRequestInput0() (CreateResponseRequestInput0, error) {
	var body CreateResponseRequestInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateResponseRequestInput0 overwrites any union data inside the CreateResponseRequest_Input as the provided CreateResponseRequestInput0
func (t *CreateResponseRequest_Input) FromCreateResponseRequestInput0(v CreateResponseRequestInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateResponseRequestInput0 performs a merge with any union data inside the CreateResponseRequest_Input, using the provided CreateResponseRequestInput0
func (t *CreateResponseRequest_Input) MergeCreateResponseRequestInput0(v CreateResponseRequestInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCreateResponseRequestInput1 returns the union data inside the CreateResponseRequest_Input as a CreateResponseRequestInput1
func (t CreateResponseRequest_Input) AsCreateResponseRequestInput1() (CreateResponseRequestInput1, error) {
	var body CreateResponseRequestInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCreateResponseRequestInput1 overwrites any union data inside the CreateResponseRequest_Input as the provided CreateResponseRequestInput1
func (t *CreateResponseRequest_Input) FromCreateResponseRequestInput1(v CreateResponseRequestInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCreateResponseRequestInput1 performs a merge with any union data inside the CreateResponseRequest_Input, using the provided CreateResponseRequestInput1
func (t *CreateResponseRequest_Input) MergeCreateResponseRequestInput1(v CreateResponseRequestInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateResponseRequest_Input) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateResponseRequest_Input) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsResponseInputItemContent0 returns the union data inside the ResponseInputItem_Content as a ResponseInputItemContent0
func (t ResponseInputItem_Content) AsResponseInputItemContent0() (ResponseInputItemContent0, error) {
	var body ResponseInputItemContent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResponseInputItemContent0 overwrites any union data inside the ResponseInputItem_Content as the provided ResponseInputItemContent0
func (t *ResponseInputItem_Content) FromResponseInputItemContent0(v ResponseInputItemContent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResponseInputItemContent0 performs a merge with any union data inside the ResponseInputItem_Content, using the provided ResponseInputItemContent0
func (t *ResponseInputItem_Content) MergeResponseInputItemContent0(v ResponseInputItemContent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResponseInputItemContent1 returns the union data inside the ResponseInputItem_Content as a ResponseInputItemContent1
func (t ResponseInputItem_Content) AsResponseInputItemContent1() (ResponseInputItemContent1, error) {
	var body ResponseInputItemContent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResponseInputItemContent1 overwrites any union data inside the ResponseInputItem_Content as the provided ResponseInputItemContent1
func (t *ResponseInputItem_Content) FromResponseInputItemContent1(v ResponseInputItemContent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResponseInputItemContent1 performs a merge with any union data inside the ResponseInputItem_Content, using the provided ResponseInputItemContent1
func (t *ResponseInputItem_Content) MergeResponseInputItemContent1(v ResponseInputItemContent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResponseInputItem_Content) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResponseInputItem_Content) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
