// Code generated by oapi-codegen v2.8.0 from packages/contracts/openapi/executor/v1.yaml (Chi and strict server).
// DO NOT EDIT. Regenerate via: packages/contracts/go/generate-executor.sh

// Package executorv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package executorv1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ExecutorGetHealthz Liveness probe
	// (GET /healthz)
	ExecutorGetHealthz(w http.ResponseWriter, r *http.Request)
	// ExecutorHeadHealthz Liveness probe (HEAD)
	// (HEAD /healthz)
	ExecutorHeadHealthz(w http.ResponseWriter, r *http.Request)
	// CreateChatCompletion Create chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(w http.ResponseWriter, r *http.Request)
	// CreateImage Create image generation
	// (POST /v1/images/generations)
	CreateImage(w http.ResponseWriter, r *http.Request)
	// CreateMessage Create message (Anthropic)
	// (POST /v1/messages)
	CreateMessage(w http.ResponseWriter, r *http.Request)
	// ListModels List available models
	// (GET /v1/models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// CreateResponse Create response (OpenAI Responses API)
	// (POST /v1/responses)
	CreateResponse(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ExecutorGetHealthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) ExecutorGetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExecutorHeadHealthz Liveness probe (HEAD)
// (HEAD /healthz)
func (_ Unimplemented) ExecutorHeadHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateChatCompletion Create chat completion
// (POST /v1/chat/completions)
func (_ Unimplemented) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateImage Create image generation
// (POST /v1/images/generations)
func (_ Unimplemented) CreateImage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateMessage Create message (Anthropic)
// (POST /v1/messages)
func (_ Unimplemented) CreateMessage(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListModels List available models
// (GET /v1/models)
func (_ Unimplemented) ListModels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateResponse Create response (OpenAI Responses API)
// (POST /v1/responses)
func (_ Unimplemented) CreateResponse(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ExecutorGetHealthz operation middleware
func (siw *ServerInterfaceWrapper) ExecutorGetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecutorGetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExecutorHeadHealthz operation middleware
func (siw *ServerInterfaceWrapper) ExecutorHeadHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExecutorHeadHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChatCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChatCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateImage operation middleware
func (siw *ServerInterfaceWrapper) CreateImage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateImage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMessage operation middleware
func (siw *ServerInterfaceWrapper) CreateMessage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMessage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateResponse operation middleware
func (siw *ServerInterfaceWrapper) CreateResponse(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateResponse(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.ExecutorGetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/healthz", wrapper.ExecutorHeadHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/models", wrapper.ListModels)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/chat/completions", wrapper.CreateChatCompletion)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/messages", wrapper.CreateMessage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/responses", wrapper.CreateResponse)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/images/generations", wrapper.CreateImage)
	})

	return r
}

type AnthropicBadRequestJSONResponse AnthropicErrorResponse

type AnthropicNotFoundJSONResponse AnthropicErrorResponse

type AnthropicNotImplementedJSONResponse AnthropicErrorResponse

type AnthropicOverloadedJSONResponse AnthropicErrorResponse

type AnthropicPermissionDeniedJSONResponse AnthropicErrorResponse

type AnthropicRateLimitResponseHeaders struct {
	RetryAfter *int
}
type AnthropicRateLimitJSONResponse struct {
	Body AnthropicErrorResponse

	Headers AnthropicRateLimitResponseHeaders
}

type AnthropicServerErrorJSONResponse AnthropicErrorResponse

type AnthropicUnauthorizedJSONResponse AnthropicErrorResponse

type OpenAIBadRequestJSONResponse OpenAIErrorResponse

type OpenAINotFoundJSONResponse OpenAIErrorResponse

type OpenAINotImplementedJSONResponse OpenAIErrorResponse

type OpenAIPermissionDeniedJSONResponse OpenAIErrorResponse

type OpenAIRateLimitResponseHeaders struct {
	RetryAfter *int
}
type OpenAIRateLimitJSONResponse struct {
	Body OpenAIErrorResponse

	Headers OpenAIRateLimitResponseHeaders
}

type OpenAIServerErrorJSONResponse OpenAIErrorResponse

type OpenAIUnauthorizedJSONResponse OpenAIErrorResponse

type OpenAIUpstreamErrorJSONResponse OpenAIErrorResponse

type ExecutorGetHealthzRequestObject struct {
}

type ExecutorGetHealthzResponseObject interface {
	VisitExecutorGetHealthzResponse(w http.ResponseWriter) error
}

type ExecutorGetHealthz200ResponseHeaders struct {
	CacheControl *string
}

type ExecutorGetHealthz200JSONResponse struct {
	Body    HealthResponse
	Headers ExecutorGetHealthz200ResponseHeaders
}

func (response ExecutorGetHealthz200JSONResponse) VisitExecutorGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExecutorGetHealthz405Response struct {
}

func (response ExecutorGetHealthz405Response) VisitExecutorGetHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(405)
	return nil
}

type ExecutorHeadHealthzRequestObject struct {
}

type ExecutorHeadHealthzResponseObject interface {
	VisitExecutorHeadHealthzResponse(w http.ResponseWriter) error
}

type ExecutorHeadHealthz200ResponseHeaders struct {
	CacheControl *string
}

type ExecutorHeadHealthz200Response struct {
	Headers ExecutorHeadHealthz200ResponseHeaders
}

func (response ExecutorHeadHealthz200Response) VisitExecutorHeadHealthzResponse(w http.ResponseWriter) error {
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)
	return nil
}

type ExecutorHeadHealthz405Response struct {
}

func (response ExecutorHeadHealthz405Response) VisitExecutorHeadHealthzResponse(w http.ResponseWriter) error {
	w.WriteHeader(405)
	return nil
}

type CreateChatCompletionRequestObject struct {
	Body *CreateChatCompletionJSONRequestBody
}

type CreateChatCompletionResponseObject interface {
	VisitCreateChatCompletionResponse(w http.ResponseWriter) error
}

type CreateChatCompletion200JSONResponse ChatCompletionResponse

func (response CreateChatCompletion200JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateChatCompletion200TexteventStreamResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateChatCompletion400JSONResponse struct{ OpenAIBadRequestJSONResponse }

func (response CreateChatCompletion400JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion401JSONResponse struct{ OpenAIUnauthorizedJSONResponse }

func (response CreateChatCompletion401JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion403JSONResponse struct {
	OpenAIPermissionDeniedJSONResponse
}

func (response CreateChatCompletion403JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion404JSONResponse struct{ OpenAINotFoundJSONResponse }

func (response CreateChatCompletion404JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion429JSONResponse struct{ OpenAIRateLimitJSONResponse }

func (response CreateChatCompletion429JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion500JSONResponse struct{ OpenAIServerErrorJSONResponse }

func (response CreateChatCompletion500JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion501JSONResponse struct {
	OpenAINotImplementedJSONResponse
}

func (response CreateChatCompletion501JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion502JSONResponse struct {
	OpenAIUpstreamErrorJSONResponse
}

func (response CreateChatCompletion502JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImageRequestObject struct {
	Body *CreateImageJSONRequestBody
}

type CreateImageResponseObject interface {
	VisitCreateImageResponse(w http.ResponseWriter) error
}

type CreateImage200JSONResponse CreateImageResponse

func (response CreateImage200JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage400JSONResponse struct{ OpenAIBadRequestJSONResponse }

func (response CreateImage400JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage401JSONResponse struct{ OpenAIUnauthorizedJSONResponse }

func (response CreateImage401JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage404JSONResponse struct{ OpenAINotFoundJSONResponse }

func (response CreateImage404JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage429JSONResponse struct{ OpenAIRateLimitJSONResponse }

func (response CreateImage429JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage500JSONResponse struct{ OpenAIServerErrorJSONResponse }

func (response CreateImage500JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage501JSONResponse struct {
	OpenAINotImplementedJSONResponse
}

func (response CreateImage501JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateImage502JSONResponse struct {
	OpenAIUpstreamErrorJSONResponse
}

func (response CreateImage502JSONResponse) VisitCreateImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessageRequestObject struct {
	Body *CreateMessageJSONRequestBody
}

type CreateMessageResponseObject interface {
	VisitCreateMessageResponse(w http.ResponseWriter) error
}

type CreateMessage200JSONResponse CreateMessageResponse

func (response CreateMessage200JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateMessage200TexteventStreamResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateMessage400JSONResponse struct {
	AnthropicBadRequestJSONResponse
}

func (response CreateMessage400JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage401JSONResponse struct {
	AnthropicUnauthorizedJSONResponse
}

func (response CreateMessage401JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage403JSONResponse struct {
	AnthropicPermissionDeniedJSONResponse
}

func (response CreateMessage403JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage404JSONResponse struct{ AnthropicNotFoundJSONResponse }

func (response CreateMessage404JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage429JSONResponse struct{ AnthropicRateLimitJSONResponse }

func (response CreateMessage429JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage500JSONResponse struct {
	AnthropicServerErrorJSONResponse
}

func (response CreateMessage500JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage501JSONResponse struct {
	AnthropicNotImplementedJSONResponse
}

func (response CreateMessage501JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMessage529JSONResponse struct {
	AnthropicOverloadedJSONResponse
}

func (response CreateMessage529JSONResponse) VisitCreateMessageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(529)
	_, err := buf.WriteTo(w)
	return err
}

type ListModelsRequestObject struct {
}

type ListModelsResponseObject interface {
	VisitListModelsResponse(w http.ResponseWriter) error
}

type ListModels200JSONResponse ModelListResponse

func (response ListModels200JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListModels401JSONResponse struct{ OpenAIUnauthorizedJSONResponse }

func (response ListModels401JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListModels500JSONResponse struct{ OpenAIServerErrorJSONResponse }

func (response ListModels500JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListModels501JSONResponse struct {
	OpenAINotImplementedJSONResponse
}

func (response ListModels501JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponseRequestObject struct {
	Body *CreateResponseJSONRequestBody
}

type CreateResponseResponseObject interface {
	VisitCreateResponseResponse(w http.ResponseWriter) error
}

type CreateResponse200JSONResponse ResponseResponse

func (response CreateResponse200JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateResponse200TexteventStreamResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateResponse400JSONResponse struct{ OpenAIBadRequestJSONResponse }

func (response CreateResponse400JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse401JSONResponse struct{ OpenAIUnauthorizedJSONResponse }

func (response CreateResponse401JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse403JSONResponse struct {
	OpenAIPermissionDeniedJSONResponse
}

func (response CreateResponse403JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse404JSONResponse struct{ OpenAINotFoundJSONResponse }

func (response CreateResponse404JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse429JSONResponse struct{ OpenAIRateLimitJSONResponse }

func (response CreateResponse429JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse500JSONResponse struct{ OpenAIServerErrorJSONResponse }

func (response CreateResponse500JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse501JSONResponse struct {
	OpenAINotImplementedJSONResponse
}

func (response CreateResponse501JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateResponse502JSONResponse struct {
	OpenAIUpstreamErrorJSONResponse
}

func (response CreateResponse502JSONResponse) VisitCreateResponseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ExecutorGetHealthz Liveness probe
	// (GET /healthz)
	ExecutorGetHealthz(ctx context.Context, request ExecutorGetHealthzRequestObject) (ExecutorGetHealthzResponseObject, error)
	// ExecutorHeadHealthz Liveness probe (HEAD)
	// (HEAD /healthz)
	ExecutorHeadHealthz(ctx context.Context, request ExecutorHeadHealthzRequestObject) (ExecutorHeadHealthzResponseObject, error)
	// CreateChatCompletion Create chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(ctx context.Context, request CreateChatCompletionRequestObject) (CreateChatCompletionResponseObject, error)
	// CreateImage Create image generation
	// (POST /v1/images/generations)
	CreateImage(ctx context.Context, request CreateImageRequestObject) (CreateImageResponseObject, error)
	// CreateMessage Create message (Anthropic)
	// (POST /v1/messages)
	CreateMessage(ctx context.Context, request CreateMessageRequestObject) (CreateMessageResponseObject, error)
	// ListModels List available models
	// (GET /v1/models)
	ListModels(ctx context.Context, request ListModelsRequestObject) (ListModelsResponseObject, error)
	// CreateResponse Create response (OpenAI Responses API)
	// (POST /v1/responses)
	CreateResponse(ctx context.Context, request CreateResponseRequestObject) (CreateResponseResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ExecutorGetHealthz operation middleware
func (sh *strictHandler) ExecutorGetHealthz(w http.ResponseWriter, r *http.Request) {
	var request ExecutorGetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExecutorGetHealthz(ctx, request.(ExecutorGetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExecutorGetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExecutorGetHealthzResponseObject); ok {
		if err := validResponse.VisitExecutorGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExecutorHeadHealthz operation middleware
func (sh *strictHandler) ExecutorHeadHealthz(w http.ResponseWriter, r *http.Request) {
	var request ExecutorHeadHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExecutorHeadHealthz(ctx, request.(ExecutorHeadHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExecutorHeadHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExecutorHeadHealthzResponseObject); ok {
		if err := validResponse.VisitExecutorHeadHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChatCompletion operation middleware
func (sh *strictHandler) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {
	var request CreateChatCompletionRequestObject

	var body CreateChatCompletionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatCompletion(ctx, request.(CreateChatCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatCompletion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChatCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChatCompletionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateImage operation middleware
func (sh *strictHandler) CreateImage(w http.ResponseWriter, r *http.Request) {
	var request CreateImageRequestObject

	var body CreateImageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateImage(ctx, request.(CreateImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateImage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateImageResponseObject); ok {
		if err := validResponse.VisitCreateImageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMessage operation middleware
func (sh *strictHandler) CreateMessage(w http.ResponseWriter, r *http.Request) {
	var request CreateMessageRequestObject

	var body CreateMessageJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMessage(ctx, request.(CreateMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMessage")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMessageResponseObject); ok {
		if err := validResponse.VisitCreateMessageResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListModels operation middleware
func (sh *strictHandler) ListModels(w http.ResponseWriter, r *http.Request) {
	var request ListModelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListModels(ctx, request.(ListModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListModelsResponseObject); ok {
		if err := validResponse.VisitListModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateResponse operation middleware
func (sh *strictHandler) CreateResponse(w http.ResponseWriter, r *http.Request) {
	var request CreateResponseRequestObject

	var body CreateResponseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateResponse(ctx, request.(CreateResponseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateResponse")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateResponseResponseObject); ok {
		if err := validResponse.VisitCreateResponseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
